TEMU: disasm.h File Reference
TEMU: Dynamic Binary Analysis Platform
disasm.h File Reference
Data Structures
struct _basic_block
struct _element
struct _float_register
struct _function
struct _hash_table
struct _immediate
struct _inst_digraph_node
struct _inst_digraphs
struct _jump
struct _mem_loc
struct _obfuscation_params
struct _queue
struct _register
struct _segment
struct disassemble_info
struct i386_instruction
struct i386_op
struct i386_operand
union i386_operand::i386_operand::OpValue
Typedefs
typedef struct _basic_block BasicBlock
typedef struct _element Element
typedef struct _float_register FloatRegister
typedef struct _function Function
typedef struct _hash_table HashTable
typedef struct _immediate Immediate
typedef struct _inst_digraph_node InstDigraphNode
typedef struct _inst_digraphs InstDigraphs
typedef struct i386_instruction Instruction
typedef struct _jump Jump
typedef struct _mem_loc MemLoc
typedef struct _obfuscation_params ObfuscationParams
typedef void(* op_rtn)(Instruction *, int, int)
typedef struct i386_operand Operand
typedef struct _queue Queue
typedef struct _register Register
typedef struct _segment Segment
Enumerations
enum OpType {
TNone = 0, TRegister, TMemLoc, TImmediate,
TJump, TFloatRegister, TMemAddress
}
Functions
void append (Queue *, bfd_vma, void *)
int buffer_read_memory (bfd_vma memaddr, bfd_byte *myaddr, unsigned int length, struct disassemble_info *info)
float detect_junk_insts (bfd_vma start, bfd_vma end)
void disassemble_i386_data (bfd *abfd, int print_insn_digraphs, int interactive)
void disassemble_segment_i386 (bfd *abfd, struct disassemble_info *info, bfd_vma from, bfd_vma to)
void fatal (const char *fmt,...)
int get_control_transfer_type (struct i386_instruction *inst, bfd_vma *target)
struct i386_instruction * get_i386_insn (struct disassemble_info *info, bfd_vma offset, struct _segment *segment)
struct i386_instruction * get_i386_insn_buf (const char *buf, size_t size)
int get_i386_insn_length (const char *buf)
struct i386_instruction * get_inst_of (bfd_vma pc)
struct _segment * get_segment_of (bfd_vma addr)
unsigned int hash (bfd_vma addr)
void hclear (HashTable *)
void * hdelete (HashTable *ht, bfd_vma)
int hexists (HashTable *, bfd_vma)
void hupdate (HashTable *, bfd_vma)
unsigned char indep_regnum (unsigned char reg)
void init_disasm_info (struct disassemble_info *disasm_info, struct _segment *segment)
void insert (HashTable *, bfd_vma, void *)
float inst_count_get (InstDigraphs *g, Instruction *i)
unsigned int inst_count_hash (unsigned char *o)
unsigned int inst_count_node_equals (InstDigraphNode *n, unsigned char *o)
void inst_count_put (InstDigraphs *g, unsigned char *o, unsigned int c)
void inst_digraph_destroy (InstDigraphs *g)
float inst_digraph_get (InstDigraphs *g, Instruction *i1, Instruction *i2)
unsigned int inst_digraph_hash (unsigned char *o1, unsigned char *o2)
void inst_digraph_incr (InstDigraphs *g, Instruction *i1, Instruction *i2)
void inst_digraph_init (InstDigraphs *g)
unsigned int inst_digraph_node_equals (InstDigraphNode *n, unsigned char *o1, unsigned char *o2)
void inst_digraph_parse (InstDigraphs *g, FILE *s)
void inst_digraph_print (InstDigraphs *g)
void inst_digraph_put (InstDigraphs *g, unsigned char *o1, unsigned char *o2, unsigned int c)
unsigned int is_div (Instruction *i)
int is_insn_supported (struct i386_instruction *inst)
unsigned int is_mov (Instruction *i)
unsigned int is_mul (Instruction *i)
unsigned int is_shift (Instruction *i)
unsigned int is_special_reg (Operand *o)
unsigned int is_uncommon_arithmetic (Instruction *i)
void OP_DIR (Instruction *, int, int)
void OP_DSreg (Instruction *, int, int)
void OP_E (Instruction *, int, int)
void OP_ESreg (Instruction *, int, int)
void OP_G (Instruction *, int, int)
void OP_I (Instruction *, int, int)
void OP_IMREG (Instruction *, int, int)
void OP_indirE (Instruction *, int, int)
void OP_J (Instruction *, int, int)
void OP_OFF (Instruction *, int, int)
void OP_REG (Instruction *, int, int)
void OP_SEG (Instruction *, int, int)
void OP_sI (Instruction *, int, int)
void OP_ST (Instruction *, int, int)
void OP_STi (Instruction *, int, int)
unsigned char op_width (Operand *op)
bfd_vma pop (Queue *)
void print_i386_insn (struct i386_instruction *inst, int type)
void print_i386_rawbytes (bfd_vma addr, const char *buf, ssize_t size)
void push (Queue *, bfd_vma, void *)
void qclear (Queue *)
void * qdelete (Queue *, bfd_vma)
int qexists (Queue *, bfd_vma)
unsigned char reg_width (unsigned char reg)
void * retrieve (HashTable *, bfd_vma)
float score_junk_insts (Instruction *last, Instruction *cur)
float update_junk_score (Instruction *newinstr, Instruction *next, float orig, unsigned int num)
void * xalloc (size_t num, size_t size)
Variables
int debug
InstDigraphs digraphs
const char * fgrps [][8]
const char * float_mem []
struct i386_op float_reg [][8]
struct i386_op i386_group_1 [][8]
struct i386_op i386_group_2 [][8]
struct i386_op i386_op_1 []
struct i386_op i386_op_2 []
const char * intel_index16 []
const char * intel_names16 []
const char * intel_names32 []
const char * intel_names8 []
const char * intel_names_seg []
const unsigned char onebyte_has_modrm [256]
const unsigned char onebyte_is_group [256]
int show_asm
int statistics
const unsigned char twobyte_has_modrm [256]
const unsigned char twobyte_is_group [256]
const unsigned char twobyte_uses_SSE_prefix [256]
Typedef Documentation
typedef struct _basic_block BasicBlock
typedef struct _element Element
typedef struct _float_register FloatRegister
typedef struct _function Function
typedef struct _hash_table HashTable
typedef struct _immediate Immediate
typedef struct _inst_digraph_node InstDigraphNode
Instruction digraph node.
typedef struct _inst_digraphs InstDigraphs
Instruction digraphs.
typedef struct i386_instruction Instruction
typedef struct _jump Jump
typedef struct _mem_loc MemLoc
typedef struct _obfuscation_params ObfuscationParams
typedef void(* op_rtn)(Instruction *, int, int)
Definition at line 303 of file disasm.h.
typedef struct i386_operand Operand
typedef struct _queue Queue
typedef struct _register Register
typedef struct _segment Segment
Enumeration Type Documentation
enum OpType
Enumerator:
TNone
TRegister
TMemLoc
TImmediate
TJump
TFloatRegister
TMemAddress
Definition at line 94 of file disasm.h.
Function Documentation
void append (Queue * , bfd_vma , void *)
int buffer_read_memory (bfd_vma memaddr, bfd_byte * myaddr, unsigned int length, struct disassemble_info * info)
float detect_junk_insts (bfd_vma start, bfd_vma end)
Detect if a given run of instructions is likely junk.
Parameters:
start Start position.
end End position.
Returns:
Instruction anomaly score. (0.0 valid, 1.0 junk)
Definition at line 671 of file junk.c.
References get_segment_of(), _segment::insts, i386_instruction::length, score_junk_insts(), and _segment::start_addr.
void disassemble_i386_data (bfd * abfd, int print_insn_digraphs, int interactive)
void disassemble_segment_i386 (bfd * abfd, struct disassemble_info * info, bfd_vma from, bfd_vma to)
void fatal (const char * fmt, ...)
Referenced by inst_count_put(), inst_digraph_get(), inst_digraph_incr(), inst_digraph_put(), and op_width().
int get_control_transfer_type (struct i386_instruction * inst, bfd_vma * target)
struct i386_instruction* get_i386_insn (struct disassemble_info * info, bfd_vma offset, struct _segment * segment) [read]
struct i386_instruction* get_i386_insn_buf (const char * buf, size_t size) [read]
int get_i386_insn_length (const char * buf)
struct i386_instruction* get_inst_of (bfd_vma pc) [read]
struct _segment* get_segment_of (bfd_vma addr) [read]
Referenced by detect_junk_insts().
unsigned int hash (bfd_vma addr)
Referenced by inst_count_get(), inst_count_put(), inst_digraph_get(), inst_digraph_incr(), and inst_digraph_put().
void hclear (HashTable *)
void* hdelete (HashTable * ht, bfd_vma)
int hexists (HashTable * , bfd_vma)
void hupdate (HashTable * , bfd_vma)
unsigned char indep_regnum (unsigned char reg)
Determine addressing-mode independent register number.
Parameters:
reg Register number.
Returns:
Mode-independent number.
Definition at line 378 of file junk.c.
Referenced by score_junk_insts().
void init_disasm_info (struct disassemble_info * disasm_info, struct _segment * segment)
void insert (HashTable * , bfd_vma , void *)
float inst_count_get (InstDigraphs * g, Instruction * i)
Return probability of an instruction.
Parameters:
g Digraphs.
i Instruction.
Returns:
Probability.
Definition at line 176 of file junk.c.
References _inst_digraphs::count, _inst_digraph_node::count, _inst_digraphs::counts, hash(), inst_count_hash(), inst_count_node_equals(), _inst_digraph_node::next, and i386_instruction::opcode.
Referenced by score_junk_insts().
unsigned int inst_count_hash (unsigned char * o)
Instruction count hash function.
Parameters:
o Instruction opcodes.
Returns:
Hash value.
Definition at line 65 of file junk.c.
Referenced by inst_count_get(), inst_count_put(), inst_digraph_get(), and inst_digraph_incr().
unsigned int inst_count_node_equals (InstDigraphNode * n, unsigned char * o)
Determine if a count node is equal to an instruction.
Parameters:
n Count node.
o Instruction opcodes.
Returns:
True if equal, otherwise false.
Definition at line 80 of file junk.c.
References _inst_digraph_node::opcode.
Referenced by inst_count_get(), inst_count_put(), inst_digraph_get(), and inst_digraph_incr().
void inst_count_put (InstDigraphs * g, unsigned char * o, unsigned int c)
Put instruction count.
Parameters:
g Digraphs.
o Instruction opcodes.
c Count.
Definition at line 229 of file junk.c.
References _inst_digraph_node::count, _inst_digraphs::counts, fatal(), hash(), inst_count_hash(), inst_count_node_equals(), _inst_digraph_node::next, and _inst_digraph_node::opcode.
Referenced by inst_digraph_parse().
void inst_digraph_destroy (InstDigraphs * g)
Destroy instruction digraphs.
Parameters:
g Digraphs.
Definition at line 33 of file junk.c.
References _inst_digraphs::counts, _inst_digraphs::digraphs, and _inst_digraph_node::next.
float inst_digraph_get (InstDigraphs * g, Instruction * i1, Instruction * i2)
Return probability of an instruction digraph.
Parameters:
g Digraphs.
i1 Instruction 1.
i2 Instruction 2.
Returns:
Probability.
Definition at line 142 of file junk.c.
References _inst_digraph_node::count, _inst_digraphs::counts, _inst_digraphs::digraphs, fatal(), hash(), inst_count_hash(), inst_count_node_equals(), inst_digraph_hash(), inst_digraph_node_equals(), _inst_digraph_node::next, and i386_instruction::opcode.
Referenced by score_junk_insts().
unsigned int inst_digraph_hash (unsigned char * o1, unsigned char * o2)
Instruction digraph hash function.
Parameters:
o1 Instruction 1 opcodes.
o2 Instruction 2 opcodes.
Returns:
Hash value.
Definition at line 58 of file junk.c.
Referenced by inst_digraph_get(), inst_digraph_incr(), and inst_digraph_put().
void inst_digraph_incr (InstDigraphs * g, Instruction * i1, Instruction * i2)
Increment an instruction digraph count.
Parameters:
g Digraphs.
i1 Instruction 1.
i2 Instruction 2.
Definition at line 86 of file junk.c.
References _inst_digraphs::count, _inst_digraph_node::count, _inst_digraphs::counts, _inst_digraphs::digraphs, fatal(), hash(), inst_count_hash(), inst_count_node_equals(), inst_digraph_hash(), inst_digraph_node_equals(), _inst_digraph_node::next, _inst_digraph_node::opcode, and i386_instruction::opcode.
void inst_digraph_init (InstDigraphs * g)
Initialize instruction digraphs.
Parameters:
g Digraphs.
Definition at line 27 of file junk.c.
unsigned int inst_digraph_node_equals (InstDigraphNode * n, unsigned char * o1, unsigned char * o2)
Determine if a digraph node is equal to two instructions.
Parameters:
n Digraph node.
o1 Instruction 1 opcodes.
o2 Instruction 2 opcodes.
Returns:
True if equal, otherwise false.
Definition at line 72 of file junk.c.
References _inst_digraph_node::opcode.
Referenced by inst_digraph_get(), inst_digraph_incr(), and inst_digraph_put().
void inst_digraph_parse (InstDigraphs * g, FILE * s)
Parse serialized instruction digraphs.
Parameters:
g Digraphs.
s Input stream.
Definition at line 259 of file junk.c.
References _inst_digraphs::count, inst_count_put(), and inst_digraph_put().
void inst_digraph_print (InstDigraphs * g)
Print instruction digraphs.
Parameters:
g Digraphs.
Definition at line 347 of file junk.c.
References _inst_digraph_node::count, _inst_digraphs::count, _inst_digraphs::counts, _inst_digraphs::digraphs, _inst_digraph_node::next, and _inst_digraph_node::opcode.
void inst_digraph_put (InstDigraphs * g, unsigned char * o1, unsigned char * o2, unsigned int c)
Put count of instruction digraph.
Parameters:
g Digraphs.
o1 Instruction 1 opcodes.
o2 Instruction 2 opcodes.
c Count.
Definition at line 197 of file junk.c.
References _inst_digraph_node::count, _inst_digraphs::digraphs, fatal(), hash(), inst_digraph_hash(), inst_digraph_node_equals(), _inst_digraph_node::next, and _inst_digraph_node::opcode.
Referenced by inst_digraph_parse().
unsigned int is_div (Instruction * i)
Determine if an instruction is a DIV instruction.
Parameters:
i Instruction.
Returns:
True if DIV, otherwise false.
Definition at line 462 of file junk.c.
References i386_instruction::opcode.
Referenced by is_uncommon_arithmetic().
int is_insn_supported (struct i386_instruction * inst)
unsigned int is_mov (Instruction * i)
Print error and exit. Determine if an instruction is a MOV instruction.
Parameters:
i Instruction.
Returns:
True if MOV, otherwise false.
Definition at line 437 of file junk.c.
References i386_instruction::opcode.
Referenced by score_junk_insts().
unsigned int is_mul (Instruction * i)
Determine if an instruction is a MUL instruction.
Parameters:
i Instruction.
Returns:
True if MUL, otherwise false.
Definition at line 451 of file junk.c.
References i386_instruction::opcode.
Referenced by is_uncommon_arithmetic().
unsigned int is_shift (Instruction * i)
Determine if an instruction is a SHx instruction.
Parameters:
i Instruction.
Returns:
True if SHx, otherwise false.
Definition at line 473 of file junk.c.
References i386_instruction::opcode.
Referenced by is_uncommon_arithmetic().
unsigned int is_special_reg (Operand * o)
Determine if a register is special-purpose.
Parameters:
o Operand.
Returns:
True if special register, otherwise false.
Definition at line 492 of file junk.c.
References _register::num, i386_operand::i386_operand::OpValue::reg, and i386_operand::value.
Referenced by score_junk_insts().
unsigned int is_uncommon_arithmetic (Instruction * i)
Determine if an instruction is a less common arithmetic instruction.
Parameters:
i Instruction.
Returns:
True if less common arithmetic instruction, otherwise false.
Definition at line 484 of file junk.c.
References is_div(), is_mul(), and is_shift().
Referenced by score_junk_insts().
void OP_DIR (Instruction * , int , int)
void OP_DSreg (Instruction * , int , int)
void OP_E (Instruction * , int , int)
void OP_ESreg (Instruction * , int , int)
void OP_G (Instruction * , int , int)
void OP_I (Instruction * , int , int)
void OP_IMREG (Instruction * , int , int)
void OP_indirE (Instruction * , int , int)
void OP_J (Instruction * , int , int)
void OP_OFF (Instruction * , int , int)
void OP_REG (Instruction * , int , int)
void OP_SEG (Instruction * , int , int)
void OP_sI (Instruction * , int , int)
void OP_ST (Instruction * , int , int)
void OP_STi (Instruction * , int , int)
unsigned char op_width (Operand * op)
Determine width of operand.
Parameters:
op Operand.
Returns:
Width as addressing mode.
Definition at line 404 of file junk.c.
References fatal(), i386_operand::i386_operand::OpValue::freg, i386_operand::i386_operand::OpValue::imm, i386_operand::i386_operand::OpValue::jmp, _float_register::num, _register::num, i386_operand::i386_operand::OpValue::reg, reg_width(), TFloatRegister, TImmediate, TJump, TMemLoc, TRegister, _jump::type, _immediate::type, i386_operand::type, and i386_operand::value.
Referenced by score_junk_insts().
bfd_vma pop (Queue *)
void print_i386_insn (struct i386_instruction * inst, int type)
void print_i386_rawbytes (bfd_vma addr, const char * buf, ssize_t size)
void push (Queue * , bfd_vma , void *)
void qclear (Queue *)
void* qdelete (Queue * , bfd_vma)
int qexists (Queue * , bfd_vma)
unsigned char reg_width (unsigned char reg)
Determine width of register.
Parameters:
reg Register number.
Returns:
Register width as addressing mode.
Definition at line 391 of file junk.c.
Referenced by op_width().
void* retrieve (HashTable * , bfd_vma)
float score_junk_insts (Instruction * last, Instruction * cur)
Return a junk score for two instructions.
Parameters:
last Last instruction.
cur Current instruction.
Returns:
Junk instruction score.
Definition at line 565 of file junk.c.
References _mem_loc::base, indep_regnum(), inst_count_get(), inst_digraph_get(), is_bad_instruction(), is_mov(), is_special_reg(), is_uncommon_arithmetic(), i386_instruction::length, i386_operand::i386_operand::OpValue::mem, i386_instruction::modrm, _register::num, op_width(), i386_instruction::opcode, i386_instruction::ops, i386_operand::i386_operand::OpValue::reg, TMemLoc, TNone, TRegister, i386_operand::type, and i386_operand::value.
Referenced by detect_junk_insts(), and update_junk_score().
float update_junk_score (Instruction * newinstr, Instruction * next, float orig, unsigned int num)
Update a previously-computed junk instruction score taking into account a new instruction which prefaces the previous run.
Parameters:
new New instruction.
next Next instruction.
orig Original score.
num Length of original run.
Returns:
Updated junk score.
Definition at line 652 of file junk.c.
References score_junk_insts().
void* xalloc (size_t num, size_t size)
Variable Documentation
int debug
InstDigraphs digraphs
Instruction digraphs
Definition at line 24 of file junk.c.
const char* fgrps[][8]
Referenced by is_bad_instruction().
const char* float_mem[]
Referenced by is_bad_instruction().
struct i386_op float_reg[][8]
Referenced by is_bad_instruction().
struct i386_op i386_group_1[][8]
Referenced by is_bad_instruction().
struct i386_op i386_group_2[][8]
struct i386_op i386_op_1[]
Referenced by is_bad_instruction().
struct i386_op i386_op_2[]
Referenced by is_bad_instruction().
const char* intel_index16[]
const char* intel_names16[]
const char* intel_names32[]
const char* intel_names8[]
const char* intel_names_seg[]
const unsigned char onebyte_has_modrm[256]
const unsigned char onebyte_is_group[256]
Referenced by is_bad_instruction().
int show_asm
int statistics
const unsigned char twobyte_has_modrm[256]
const unsigned char twobyte_is_group[256]
const unsigned char twobyte_uses_SSE_prefix[256]