TEMU: function_map.h File Reference
TEMU: Dynamic Binary Analysis Platform
function_map.h File Reference
Data Structures
struct names_t
Functions
void add_fun_to_hook (const char *module_name, const char *function_name, uint32_t hookfn, int is_global)
void function_map_cleanup ()
void function_map_init ()
const char * function_map_search (uint32_t eip)
void handle_message (char *message)
void map_to_file (const char *filename)
uint32_t query_eip (const char *module_name, const char *function_name)
struct names_t * query_name (unsigned long eip)
Function Documentation
void add_fun_to_hook (const char * module_name, const char * function_name, uint32_t hookfn, int is_global)
Definition at line 141 of file function_map.cpp.
References fun_to_hook, fnhook_info_t::function, fnhook_info_t::hook, fnhook_info_t::is_global, and fnhook_info_t::module.
Referenced by hookapi_hook_function_byname().
void function_map_cleanup ()
Definition at line 490 of file function_map.cpp.
References deregister_savevm(), fun_to_hook, g_eip_map, and g_function_map.
void function_map_init ()
Definition at line 484 of file function_map.cpp.
References function_map_load(), function_map_save(), and register_savevm().
const char* function_map_search (uint32_t eip)
Given an EIP, it returns the corresponding function name if exists
Definition at line 98 of file function_map.cpp.
References g_function_map.
void handle_message (char * message)
Definition at line 260 of file function_map.cpp.
References add_rev_lookup(), g_function_map, and resolve_fun_to_hook().
Referenced by procmod_init(), unserialize_maps(), and update_proc().
void map_to_file (const char * filename)
Dump the function map to a file.
Definition at line 120 of file function_map.cpp.
References g_function_map, and term_printf().
uint32_t query_eip (const char * module_name, const char * function_name)
Definition at line 217 of file function_map.cpp.
References g_eip_map.
Referenced by hookapi_hook_function_byname().
struct names_t* query_name (unsigned long eip) [read]
Definition at line 107 of file function_map.cpp.
References names_t::fun_name, g_function_map, and names_t::mod_name.