TEMU: function_map.cpp File Reference
TEMU: Dynamic Binary Analysis Platform
function_map.cpp File Reference
Data Structures
struct fnhook_info_t
struct function_t
Typedefs
typedef pair< string, string > mod_fun_t
Functions
void add_fun_to_hook (const char *module_name, const char *function_name, uint32_t hookfn, int is_global)
static void add_rev_lookup (const char *module_name, const char *function_name, uint32_t eip)
void function_map_cleanup ()
void function_map_init ()
static int function_map_load (QEMUFile *f, void *opaque, int version_id)
static void function_map_save (QEMUFile *f, void *opaque)
const char * function_map_search (uint32_t eip)
void handle_message (char *message)
void map_to_file (const char *filename)
uint32_t query_eip (const char *module_name, const char *function_name)
int query_fun_to_hook (const char *module_name, const char *function_name)
struct names_t * query_name (unsigned long eip)
uint32_t remove_fun_to_hook (const char *module_name, const char *function_name)
static void resolve_fun_to_hook (const char *module, const char *function, uint32_t eip)
static int serialize_maps (char *buf, int buf_size)
static void unserialize_maps (const char *buf, int buf_size)
Variables
list< fnhook_info_t > fun_to_hook
map< string, map< string,
uint32_t > * > g_eip_map
map< uint32_t, function_t > g_function_map
Typedef Documentation
typedef pair<string, string> mod_fun_t
Definition at line 85 of file function_map.cpp.
Function Documentation
void add_fun_to_hook (const char * module_name, const char * function_name, uint32_t hookfn, int is_global)
Definition at line 141 of file function_map.cpp.
References fun_to_hook, fnhook_info_t::function, fnhook_info_t::hook, fnhook_info_t::is_global, and fnhook_info_t::module.
Referenced by hookapi_hook_function_byname().
static void add_rev_lookup (const char * module_name, const char * function_name, uint32_t eip) [static]
Definition at line 237 of file function_map.cpp.
References g_eip_map.
Referenced by handle_message().
void function_map_cleanup ()
Definition at line 490 of file function_map.cpp.
References deregister_savevm(), fun_to_hook, g_eip_map, and g_function_map.
void function_map_init ()
Definition at line 484 of file function_map.cpp.
References function_map_load(), function_map_save(), and register_savevm().
static int function_map_load (QEMUFile * f, void * opaque, int version_id) [static]
Definition at line 459 of file function_map.cpp.
References qemu_get_be32(), and unserialize_maps().
Referenced by function_map_init().
static void function_map_save (QEMUFile * f, void * opaque) [static]
Definition at line 440 of file function_map.cpp.
References qemu_put_be32(), and serialize_maps().
Referenced by function_map_init().
const char* function_map_search (uint32_t eip)
Given an EIP, it returns the corresponding function name if exists
Definition at line 98 of file function_map.cpp.
References g_function_map.
void handle_message (char * message)
Definition at line 260 of file function_map.cpp.
References add_rev_lookup(), g_function_map, and resolve_fun_to_hook().
Referenced by procmod_init(), unserialize_maps(), and update_proc().
void map_to_file (const char * filename)
Dump the function map to a file.
Definition at line 120 of file function_map.cpp.
References g_function_map, and term_printf().
uint32_t query_eip (const char * module_name, const char * function_name)
Definition at line 217 of file function_map.cpp.
References g_eip_map.
Referenced by hookapi_hook_function_byname().
int query_fun_to_hook (const char * module_name, const char * function_name)
Definition at line 198 of file function_map.cpp.
References fun_to_hook.
struct names_t* query_name (unsigned long eip) [read]
Definition at line 107 of file function_map.cpp.
References names_t::fun_name, g_function_map, and names_t::mod_name.
uint32_t remove_fun_to_hook (const char * module_name, const char * function_name)
Definition at line 173 of file function_map.cpp.
References fun_to_hook.
static void resolve_fun_to_hook (const char * module, const char * function, uint32_t eip) [static]
Definition at line 155 of file function_map.cpp.
References fun_to_hook, hookapi_hook_function(), and term_printf().
Referenced by handle_message().
static int serialize_maps (char * buf, int buf_size) [static]
Definition at line 353 of file function_map.cpp.
References g_function_map.
Referenced by function_map_save().
static void unserialize_maps (const char * buf, int buf_size) [static]
Definition at line 418 of file function_map.cpp.
References handle_message().
Referenced by function_map_load().
Variable Documentation
list<fnhook_info_t> fun_to_hook
Definition at line 94 of file function_map.cpp.
Referenced by add_fun_to_hook(), function_map_cleanup(), query_fun_to_hook(), remove_fun_to_hook(), and resolve_fun_to_hook().
map<string, map <string, uint32_t > *> g_eip_map
Definition at line 79 of file function_map.cpp.
Referenced by add_rev_lookup(), function_map_cleanup(), and query_eip().
map<uint32_t, function_t > g_function_map
Definition at line 76 of file function_map.cpp.
Referenced by function_map_cleanup(), function_map_search(), handle_message(), map_to_file(), query_name(), and serialize_maps().