TEMU: temu: Main TEMU Module
TEMU: Dynamic Binary Analysis Platform
temu: Main TEMU Module
Data Structures
struct plugin_interface_t
primary structure for TEMU plugin, including callbacks and states
struct term_cmd_t
structure for defining a terminal command
Functions
void cpu_physical_memory_rw (target_phys_addr_t addr, uint8_t *buf, int len, int is_write)
read or write a physical memory region
int deregister_savevm (const char *idstr, int instance_id)
Deregister a VM entity.
void do_loadvm (const char *name)
Load a previously saved VM snapshot.
void do_savevm (const char *name)
Save the current VM states into a snapshot.
void do_send_key (const char *string)
Send a keystroke.
void qemu_del_timer (QEMUTimer *ts)
void qemu_free_timer (QEMUTimer *ts)
Free a timer.
void qemu_mod_timer (QEMUTimer *ts, int64_t expire_time)
Set up a timeout.
QEMUTimer * qemu_new_timer (QEMUClock *clock, QEMUTimerCB *cb, void *opaque)
Create a timer.
int qemu_timer_pending (QEMUTimer *ts)
Check if the timer is pending.
int register_savevm (const char *idstr, int instance_id, int version_id, SaveStateHandler *save_state, LoadStateHandler *load_state, void *opaque)
Register a VM entity for saving and restoring VM states.
int TEMU_get_page_access (uint32_t addr)
Given a virtual address, this function returns the page access status.
target_ulong TEMU_get_phys_addr (target_ulong addr)
Convert virtual address into physical address.
static int TEMU_is_in_kernel ()
Check if the current execution of guest system is in kernel mode (i.e., ring-0).
int TEMU_memory_rw (uint32_t addr, void *buf, int len, int is_write)
int TEMU_read_mem (uint32_t vaddr, int len, void *buf)
Read from a memory region by its virtual address.
int TEMU_read_mem_with_cr3 (target_ulong cr3, uint32_t vaddr, int len, void *buf)
void TEMU_read_register (int reg_id, void *buf)
Read from a register.
void TEMU_stop_vm ()
Pause the guest system.
int TEMU_write_mem (uint32_t vaddr, int len, void *buf)
Write into a memory region by its virtual address.
int TEMU_write_mem_with_cr3 (target_ulong cr3, uint32_t vaddr, int len, void *buf)
void TEMU_write_register (int reg_id, void *buf)
Write into a register.
void term_printf (const char *fmt,...)
print a message to TEMU terminal
void vm_stop (int reason)
Pause VM.
Variables
uint32_t * TEMU_cc_op
target_ulong * TEMU_cpu_cr
array of CPU control registers, such as CR0 and CR1
int32_t * TEMU_cpu_df
pointer to DF register
target_ulong * TEMU_cpu_eflags
pointer to EFLAGS
target_ulong * TEMU_cpu_eip
pointer to instruction pointer EIP
FPReg * TEMU_cpu_fp_regs
FPU - array of Floating Point registers.
unsigned int * TEMU_cpu_fp_stt
FPU - top of Floating Point register stack.
uint8_t * TEMU_cpu_fptags
FPU - Tag Register.
unsigned int * TEMU_cpu_fpuc
FPU - Control Register.
unsigned int * TEMU_cpu_fpus
FPU - Status Register.
SegmentCache * TEMU_cpu_gdt
pointer to GDT
uint32_t * TEMU_cpu_hflags
pointer to hidden flags
SegmentCache * TEMU_cpu_idt
pointer to IDT
SegmentCache * TEMU_cpu_ldt
pointer to LDT
MMXReg * TEMU_cpu_mmx_regs
array of MMX registers
target_ulong * TEMU_cpu_regs
array of CPU general-purpose registers, such as R_EAX, R_EBX
SegmentCache * TEMU_cpu_segs
array of CPU segment registers, such as R_FS, R_CS
XMMReg * TEMU_cpu_xmm_regs
array of XMM registers
int TEMU_emulation_started
This flag tells if emulation mode is enabled.
Detailed Description
Additional documentation for group 'main'
Function Documentation
void cpu_physical_memory_rw (target_phys_addr_t addr, uint8_t * buf, int len, int is_write)
read or write a physical memory region
Parameters:
addr physical address
buf buffer (output buffer for read and input buffer for write)
len length of memory region
is_write true for write and false for read
Referenced by TEMU_memory_rw(), and TEMU_memory_rw_with_cr3().
int deregister_savevm (const char * idstr, int instance_id)
Deregister a VM entity.
Referenced by function_map_cleanup(), hookapi_cleanup(), procmod_cleanup(), and taintcheck_cleanup().
void do_loadvm (const char * name)
Load a previously saved VM snapshot.
Referenced by TEMU_loadvm().
void do_savevm (const char * name)
Save the current VM states into a snapshot.
void do_send_key (const char * string)
Send a keystroke.
send a keystroke into the guest system
void qemu_del_timer (QEMUTimer * ts)
void qemu_free_timer (QEMUTimer * ts)
Free a timer.
void qemu_mod_timer (QEMUTimer * ts, int64_t expire_time)
Set up a timeout.
QEMUTimer* qemu_new_timer (QEMUClock * clock, QEMUTimerCB * cb, void * opaque)
Create a timer.
int qemu_timer_pending (QEMUTimer * ts)
Check if the timer is pending.
int register_savevm (const char * idstr, int instance_id, int version_id, SaveStateHandler * save_state, LoadStateHandler * load_state, void * opaque)
Register a VM entity for saving and restoring VM states.
Referenced by function_map_init(), init_hookapi(), procmod_init(), taintcheck_create(), and TEMU_init().
int TEMU_get_page_access (uint32_t addr)
Given a virtual address, this function returns the page access status.
Parameters:
addr virtual memory address
Returns:
page access status: -1 means not present, 0 means readonly, and 1 means writable.
Definition at line 565 of file TEMU_main.c.
References first_cpu.
target_ulong TEMU_get_phys_addr (target_ulong addr)
Convert virtual address into physical address.
Definition at line 382 of file TEMU_main.c.
References first_cpu.
Referenced by taintcheck_check_virtmem(), taintcheck_code2TN(), taintcheck_patch(), taintcheck_taint_virtmem(), and TEMU_memory_rw().
static int TEMU_is_in_kernel () [inline, static]
Check if the current execution of guest system is in kernel mode (i.e., ring-0).
Definition at line 489 of file TEMU_main.h.
References TEMU_cpu_hflags.
Referenced by get_current_tid().
int TEMU_memory_rw (uint32_t addr, void * buf, int len, int is_write)
Definition at line 421 of file TEMU_main.c.
References cpu_physical_memory_rw(), and TEMU_get_phys_addr().
Referenced by get_mod_name(), init_kernel_offsets(), TEMU_read_mem(), and TEMU_write_mem().
int TEMU_read_mem (uint32_t vaddr, int len, void * buf)
Read from a memory region by its virtual address.
Parameters:
vaddr virtual memory address
len length of memory region (in bytes)
buf output buffer of the value to be read
Returns:
status: 0 for success and -1 for failure
If failure, it usually means that the given virtual address cannot be converted into physical address. It could be either invalid address or swapped out.
Definition at line 466 of file TEMU_main.c.
References TEMU_memory_rw().
Referenced by alloca_probe_call(), ExInterlockedPushEntryList_call(), get_current_tid(), get_first_mmap(), get_name(), get_next_mmap(), get_pgd(), get_pid(), get_vmend(), get_vmstart(), InterlockedPushEntrySList_call(), next_task_struct(), and taintcheck_patch().
int TEMU_read_mem_with_cr3 (target_ulong cr3, uint32_t vaddr, int len, void * buf)
Definition at line 476 of file TEMU_main.c.
References TEMU_memory_rw_with_cr3().
void TEMU_read_register (int reg_id, void * buf)
Read from a register.
Note that reg_id is register ID, which is different from register index. Register ID is defined by Kruegel's disassembler, whereas register index is the index of CPU register array.
Parameters:
reg_id register ID
buf output buffer of the value to be read
Definition at line 372 of file TEMU_main.c.
References TEMU_register_rw().
void TEMU_stop_vm ()
Pause the guest system.
Definition at line 627 of file TEMU_main.c.
References vm_stop().
int TEMU_write_mem (uint32_t vaddr, int len, void * buf)
Write into a memory region by its virtual address.
Parameters:
vaddr virtual memory address
len length of memory region (in bytes)
buf input buffer of the value to be written
Returns:
status: 0 for success and -1 for failure
If failure, it usually means that the given virtual address cannot be converted into physical address. It could be either invalid address or swapped out.
Definition at line 471 of file TEMU_main.c.
References TEMU_memory_rw().
int TEMU_write_mem_with_cr3 (target_ulong cr3, uint32_t vaddr, int len, void * buf)
Definition at line 481 of file TEMU_main.c.
References TEMU_memory_rw_with_cr3().
void TEMU_write_register (int reg_id, void * buf)
Write into a register.
Note that reg_id is register ID, which is different from register index. Register ID is defined by Kruegel's disassembler, whereas register index is the index of CPU register array.
Parameters:
reg_id register ID
buf input buffer of the value to be written
Definition at line 377 of file TEMU_main.c.
References TEMU_register_rw().
void term_printf (const char * fmt, ...)
print a message to TEMU terminal
Referenced by do_disable_emulation(), do_enable_emulation(), do_info_taintmem(), do_linux_ps(), do_load_plugin(), do_unload_plugin(), list_guest_modules(), list_procs(), map_to_file(), parse_plugin_ini(), and resolve_fun_to_hook().
void vm_stop (int reason)
Pause VM.
Referenced by TEMU_stop_vm().
Variable Documentation
uint32_t* TEMU_cc_op
Definition at line 40 of file TEMU_main.c.
Referenced by TEMU_update_cpustate().
target_ulong* TEMU_cpu_cr
array of CPU control registers, such as CR0 and CR1
Definition at line 38 of file TEMU_main.c.
Referenced by hookapi_check_call(), hookapi_hook_return(), and TEMU_update_cpustate().
int32_t* TEMU_cpu_df
pointer to DF register
Definition at line 39 of file TEMU_main.c.
Referenced by TEMU_update_cpustate().
target_ulong* TEMU_cpu_eflags
pointer to EFLAGS
Definition at line 32 of file TEMU_main.c.
Referenced by TEMU_update_cpustate().
target_ulong* TEMU_cpu_eip
pointer to instruction pointer EIP
Definition at line 31 of file TEMU_main.c.
Referenced by hookapi_check_call(), and TEMU_update_cpustate().
FPReg* TEMU_cpu_fp_regs
FPU - array of Floating Point registers.
Definition at line 43 of file TEMU_main.c.
unsigned int* TEMU_cpu_fp_stt
FPU - top of Floating Point register stack.
Definition at line 44 of file TEMU_main.c.
Referenced by TEMU_update_cpustate().
uint8_t* TEMU_cpu_fptags
FPU - Tag Register.
Definition at line 47 of file TEMU_main.c.
Referenced by TEMU_update_cpustate().
unsigned int* TEMU_cpu_fpuc
FPU - Control Register.
Definition at line 46 of file TEMU_main.c.
Referenced by TEMU_update_cpustate().
unsigned int* TEMU_cpu_fpus
FPU - Status Register.
Definition at line 45 of file TEMU_main.c.
Referenced by TEMU_update_cpustate().
SegmentCache* TEMU_cpu_gdt
pointer to GDT
Definition at line 36 of file TEMU_main.c.
uint32_t* TEMU_cpu_hflags
pointer to hidden flags
Definition at line 33 of file TEMU_main.c.
Referenced by TEMU_is_in_kernel(), and TEMU_update_cpustate().
SegmentCache* TEMU_cpu_idt
pointer to IDT
Definition at line 37 of file TEMU_main.c.
SegmentCache* TEMU_cpu_ldt
pointer to LDT
Definition at line 35 of file TEMU_main.c.
MMXReg* TEMU_cpu_mmx_regs
array of MMX registers
Definition at line 42 of file TEMU_main.c.
target_ulong* TEMU_cpu_regs
array of CPU general-purpose registers, such as R_EAX, R_EBX
Definition at line 30 of file TEMU_main.c.
Referenced by _aligned_offset_malloc_call(), _aligned_offset_realloc_call(), alloca_probe_call(), calloc_call(), ExAllocatePoolWithTag_call(), ExInterlockedPushEntryList_call(), hookapi_check_call(), hookapi_hook_return(), InterlockedPushEntrySList_call(), malloc_call(), NtAllocateVirtualMemory_call(), realloc_call(), RtlAllocateHeap_call(), RtlReAllocateHeap_call(), and TEMU_update_cpustate().
SegmentCache* TEMU_cpu_segs
array of CPU segment registers, such as R_FS, R_CS
Definition at line 34 of file TEMU_main.c.
Referenced by get_current_tid(), and is_guest_windows().
XMMReg* TEMU_cpu_xmm_regs
array of XMM registers
Definition at line 41 of file TEMU_main.c.
int TEMU_emulation_started
This flag tells if emulation mode is enabled.
Definition at line 26 of file TEMU_main.c.
Referenced by __attribute__(), do_disable_emulation(), do_enable_emulation(), LIST_HEAD(), taintcheck_check_eip(), taintcheck_chk_hdin(), taintcheck_chk_hdout(), taintcheck_chk_hdread(), taintcheck_chk_hdwrite(), taintcheck_clear_ones(), taintcheck_clear_zeros(), taintcheck_disk_check(), taintcheck_jnz_T0_label(), taintcheck_memory_check(), taintcheck_nic_readbuf(), taintcheck_nic_writebuf(), taintcheck_patch(), taintcheck_register_check(), taintcheck_sidt(), taintcheck_taint_memory(), taintcheck_taint_register(), TEMU_block_begin(), TEMU_call_analysis(), TEMU_insn_begin(), TEMU_insn_end(), TEMU_nic_in(), TEMU_nic_out(), and TEMU_save().