TEMU: XED-INIT: XED Initialization
TEMU: Dynamic Binary Analysis Platform
XED-INIT: XED Initialization
Data Structures
struct xed_state_s
Typedefs
typedef struct XED_DLL_EXPORT
xed_state_s xed_state_t
typedef struct XED_DLL_EXPORT
xed_state_s xed_state_t
Functions
void XED_DLL_EXPORT xed_decode_init ()
void XED_DLL_EXPORT xed_encode_init ()
XED_DLL_EXPORT char * xed_get_copyright ()
XED_DLL_EXPORT char * xed_get_version ()
XED_DLL_EXPORT void xed_register_abort_function (void(*fn)(const char *msg, const char *file, int line, void *other), void *other)
XED_DLL_EXPORT int xed_state_print (const xed_state_t *p, char *buf, int buflen)
void XED_DLL_EXPORT xed_tables_init ()
Address width
static XED_INLINE
xed_address_width_enum_t xed_state_get_address_width (const xed_state_t *p)
static XED_INLINE void xed_state_set_address_width (xed_state_t *p, xed_address_width_enum_t arg_addr_width)
Machine mode
static XED_INLINE
xed_machine_mode_enum_t xed_state_get_machine_mode (const xed_state_t *p)
static XED_INLINE xed_bool_t xed_state_long64_mode (const xed_state_t *p)
static XED_INLINE xed_bool_t xed_state_mode_width_16 (const xed_state_t *p)
static XED_INLINE xed_bool_t xed_state_mode_width_32 (const xed_state_t *p)
static XED_INLINE xed_bool_t xed_state_real_mode (const xed_state_t *p)
static XED_INLINE void xed_state_set_machine_mode (xed_state_t *p, xed_machine_mode_enum_t arg_mode)
Stack address width
static XED_INLINE
xed_address_width_enum_t xed_state_get_stack_address_width (const xed_state_t *p)
static XED_INLINE void xed_state_set_stack_address_width (xed_state_t *p, xed_address_width_enum_t arg_addr_width)
Initialization
static XED_INLINE void xed_state_init (xed_state_t *p, xed_machine_mode_enum_t arg_mmode, xed_address_width_enum_t arg_ignored, xed_address_width_enum_t arg_stack_addr_width)
static XED_INLINE void xed_state_init2 (xed_state_t *p, xed_machine_mode_enum_t arg_mmode, xed_address_width_enum_t arg_stack_addr_width)
static XED_INLINE void xed_state_zero (xed_state_t *p)
Typedef Documentation
typedef struct XED_DLL_EXPORT xed_state_s xed_state_t
Encapsulates machine modes for decoder/encoder requests. It specifies the machine operating mode as a xed_machine_mode_enum_t for decoding and encoding. The machine mode corresponds to the default data operand width for that mode. For all modes other than the 64b long mode (XED_MACHINE_MODE_LONG_64), a default addressing width, and a stack addressing width must be supplied of type xed_address_width_enum_t .
typedef struct XED_DLL_EXPORT xed_state_s xed_state_t
Encapsulates machine modes for decoder/encoder requests. It specifies the machine operating mode as a xed_machine_mode_enum_t for decoding and encoding. The machine mode corresponds to the default data operand width for that mode. For all modes other than the 64b long mode (XED_MACHINE_MODE_LONG_64), a default addressing width, and a stack addressing width must be supplied of type xed_address_width_enum_t .
Function Documentation
void XED_DLL_EXPORT xed_decode_init ()
This is the call to initialize the XED decode tables. It must be called once before using XED.
void XED_DLL_EXPORT xed_encode_init ()
This is the call to initialize the XED encode tables. It must be called once before using XED's encoder.
XED_DLL_EXPORT char * xed_get_copyright ()
Returns a copyright string.
XED_DLL_EXPORT char * xed_get_version ()
Returns a string representing XED svn commit revision and time stamp.
XED_DLL_EXPORT void xed_register_abort_function (void(*)(const char *msg, const char *file, int line, void *other) fn, void * other)
This is for registering a function to be called during XED's assert processing. If you do not register an abort function, then the system's abort function will be called. If your supplied function returns, then abort() will still be called.
Parameters:
fn This is a function pointer for a function that should handle the assertion reporting. The function pointer points to a function that takes 4 arguments: (1) msg, the assertion message, (2) file, the file name, (3) line, the line number (as an integer), and (4) other, a void pointer that is supplied as thei 2nd argument to this registration.
other This is a void* that is passed back to your supplied function fn as its 4th argument. It can be zero if you don't need this feature. You can used this to convey whatever additional context to your assertion handler (like FILE* pointers etc.).
static XED_INLINE xed_address_width_enum_t xed_state_get_address_width (const xed_state_t * p) [static]
return the address width
Definition at line 161 of file xed2-ia32/include/xed-state.h.
References XED_ADDRESS_WIDTH_16b, XED_ADDRESS_WIDTH_32b, XED_ADDRESS_WIDTH_64b, XED_ADDRESS_WIDTH_INVALID, XED_MACHINE_MODE_LEGACY_16, XED_MACHINE_MODE_LEGACY_32, XED_MACHINE_MODE_LONG_64, XED_MACHINE_MODE_LONG_COMPAT_16, XED_MACHINE_MODE_LONG_COMPAT_32, XED_MACHINE_MODE_REAL_16, and xed_state_get_machine_mode().
static XED_INLINE xed_machine_mode_enum_t xed_state_get_machine_mode (const xed_state_t * p) [static]
return the machine mode
Definition at line 112 of file xed2-ia32/include/xed-state.h.
Referenced by xed_state_get_address_width(), xed_state_long64_mode(), xed_state_mode_width_16(), xed_state_mode_width_32(), and xed_state_real_mode().
static XED_INLINE xed_address_width_enum_t xed_state_get_stack_address_width (const xed_state_t * p) [static]
Return the STACK address width
Definition at line 197 of file xed2-ia32/include/xed-state.h.
static XED_INLINE void xed_state_init (xed_state_t * p, xed_machine_mode_enum_t arg_mmode, xed_address_width_enum_t arg_ignored, xed_address_width_enum_t arg_stack_addr_width) [static]
Constructor. DEPRECATED: use xed_state_init2(). The mode, and addresses widths are enumerations that specify the number of bits. In 64b mode (XED_MACHINE_MODE_LONG_64) the address width and stack address widths are 64b (XED_ADDRESS_WIDTH_64b). In other machine modes, you must specify valid addressing widths.
Parameters:
p the pointer to the xed_state_t type
arg_mmode the machine mode of type xed_machine_mode_enum_t
arg_ignored Ignored. The addressing width is now implied by the machine mode implied by arg_mmmode.
arg_stack_addr_width the stack address width of type xed_address_width_enum_t (only required if not the mode is not XED_MACHINE_MODE_LONG_64)
Definition at line 73 of file xed2-ia32/include/xed-state.h.
static XED_INLINE void xed_state_init2 (xed_state_t * p, xed_machine_mode_enum_t arg_mmode, xed_address_width_enum_t arg_stack_addr_width) [static]
Constructor. The mode, and addresses widths are enumerations that specify the number of bits. In 64b mode (XED_MACHINE_MODE_LONG_64) the address width and stack address widths are 64b (XED_ADDRESS_WIDTH_64b). In other machine modes, you must specify valid addressing widths.
Parameters:
p the pointer to the xed_state_t type
arg_mmode the machine mode of type xed_machine_mode_enum_t
arg_stack_addr_width the stack address width of type xed_address_width_enum_t (only required if not the mode is not XED_MACHINE_MODE_LONG_64)
Definition at line 92 of file xed2-ia32/include/xed-state.h.
static XED_INLINE xed_bool_t xed_state_long64_mode (const xed_state_t * p) [static]
true iff the machine is in LONG_64 mode
Definition at line 119 of file xed2-ia32/include/xed-state.h.
References XED_MACHINE_MODE_LONG_64, and xed_state_get_machine_mode().
static XED_INLINE xed_bool_t xed_state_mode_width_16 (const xed_state_t * p) [static]
Definition at line 129 of file xed2-ia32/include/xed-state.h.
References XED_MACHINE_MODE_LEGACY_16, XED_MACHINE_MODE_LONG_COMPAT_16, and xed_state_get_machine_mode().
static XED_INLINE xed_bool_t xed_state_mode_width_32 (const xed_state_t * p) [static]
Definition at line 135 of file xed2-ia32/include/xed-state.h.
References XED_MACHINE_MODE_LEGACY_32, XED_MACHINE_MODE_LONG_COMPAT_32, and xed_state_get_machine_mode().
XED_DLL_EXPORT int xed_state_print (const xed_state_t * p, char * buf, int buflen)
static XED_INLINE xed_bool_t xed_state_real_mode (const xed_state_t * p) [static]
Definition at line 124 of file xed2-ia32/include/xed-state.h.
References XED_MACHINE_MODE_REAL_16, and xed_state_get_machine_mode().
static XED_INLINE void xed_state_set_address_width (xed_state_t * p, xed_address_width_enum_t arg_addr_width) [static]
Set the address width
Definition at line 153 of file xed2-ia32/include/xed-state.h.
static XED_INLINE void xed_state_set_machine_mode (xed_state_t * p, xed_machine_mode_enum_t arg_mode) [static]
Set the machine mode which corresponds to the default data operand size
Definition at line 143 of file xed2-ia32/include/xed-state.h.
static XED_INLINE void xed_state_set_stack_address_width (xed_state_t * p, xed_address_width_enum_t arg_addr_width) [static]
set the STACK address width
Definition at line 189 of file xed2-ia32/include/xed-state.h.
static XED_INLINE void xed_state_zero (xed_state_t * p) [static]
clear the xed_state_t
Definition at line 101 of file xed2-ia32/include/xed-state.h.
References XED_ADDRESS_WIDTH_INVALID, and XED_MACHINE_MODE_INVALID.
void XED_DLL_EXPORT xed_tables_init ()
This is the call to initialize the XED encode and decode tables. It must be called once before using XED.