TEMU: hookapi: Function Hooking Facility
TEMU: Dynamic Binary Analysis Platform
hookapi: Function Hooking Facility
Functions
void hookapi_check_call (int in_context)
uintptr_t hookapi_hook_function (int is_global, uint32_t eip, hook_proc_t fnhook, void *opaque, uint32_t sizeof_opaque)
void hookapi_hook_function_byname (const char *mod, const char *func, int is_global, hook_proc_t fnhook, void *opaque, uint32_t sizeof_opaque)
uintptr_t hookapi_hook_return (uint32_t eip, hook_proc_t fnhook, void *opaque, uint32_t sizeof_opaque)
void hookapi_remove_hook (uintptr_t handle)
Function Documentation
void hookapi_check_call (int in_context)
search and invoke the corresponding hooks at the current eip
Parameters:
in_context flag that specifies if the current execution is in the analysis context This function is usually called in plugin's block_begin callback, to check and invoke hooks. This function deals with the situation that multiple hooks are installed on the same function entry or exit. It is able to distinguish different hooks and invoke them correctly.
Definition at line 333 of file hookapi.c.
References hookapi_record::eip, TEMU_cpu_cr, TEMU_cpu_eip, and TEMU_cpu_regs.
uintptr_t hookapi_hook_function (int is_global, uint32_t eip, hook_proc_t fnhook, void * opaque, uint32_t sizeof_opaque)
install a hook at the function entry
Parameters:
is_global flag specifies if this hook should be invoked globally or only in certain execution context
eip address of function to be hooked (has to be the start of a basic block
fnhook address of function hook
opaque address of an opaque structure provided by caller (has to be globally allocated)
Returns:
a handle that uniquely specifies this hook
Definition at line 243 of file hookapi.c.
References hookapi_record::eip, hookapi_record::fnhook, hookapi_record::is_global, hookapi_record::opaque, and hookapi_record::sizeof_opaque.
Referenced by detecting_kernel(), for_all_hookpoints(), hookapi_hook_function_byname(), and resolve_fun_to_hook().
void hookapi_hook_function_byname (const char * mod, const char * func, int is_global, hook_proc_t fnhook, void * opaque, uint32_t sizeof_opaque)
install a hook at the function entry by specifying module name and function name
Parameters:
mod module name that this function is located in
func function name
flag specifies if this hook should be invoked globally or only in certain execution context
eip address of function to be hooked (has to be the start of a basic block
fnhook address of function hook
opaque address of an opaque structure provided by caller (has to be globally allocated)
Definition at line 357 of file hookapi.c.
References add_fun_to_hook(), hookapi_record::eip, hookapi_hook_function(), and query_eip().
Referenced by reduce_taint_init().
uintptr_t hookapi_hook_return (uint32_t eip, hook_proc_t fnhook, void * opaque, uint32_t sizeof_opaque)
install a hook at the function exit
Parameters:
eip function return address
fnhook address of function hook
opaque address of an opaque structure provided by caller (has to be globally allocated)
Returns:
a handle that uniquely specifies this hook The implementation of this function handles multi-threading. It means, when multple threads call the same function and register the same return address, we can distinguish different hooks, and invoke them correctly.
Definition at line 267 of file hookapi.c.
References hookapi_record::cr3, hookapi_record::eip, hookapi_record::esp, hookapi_record::fnhook, hookapi_record::is_global, hookapi_record::opaque, hookapi_record::sizeof_opaque, TEMU_cpu_cr, and TEMU_cpu_regs.
Referenced by alloca_probe_call().
void hookapi_remove_hook (uintptr_t handle)
remove a hook
Parameters:
handle hook handle returned by hookapi_hook_function or hookapi_hook_return This function will not free the opaque structure provided by the caller when installing a hook. The caller is responsible for freeing it. The exception is when the user's plugin is unloaded, the opaque structure is freed automatically to avoid memory leakage. Likewise, when a vm state (i.e. snapshot) is loaded, the opaque structure is allocated and restored automatically.
Definition at line 291 of file hookapi.c.
References hookapi_handle::handle.
Referenced by alloca_probe_ret(), and for_all_hookpoints().