TEMU: taintcheck: Dynamic Taint Analysis Engine
TEMU: Dynamic Binary Analysis Platform
taintcheck: Dynamic Taint Analysis Engine
Functions
void default_taint_propagate (int nr_src, taint_operand_t *src_oprnds, taint_operand_t *dst_oprnd, int mode)
uint64_t taintcheck_check_virtmem (uint32_t vaddr, uint32_t size, void *records)
int taintcheck_get_sizeof_taintmem ()
uint64_t taintcheck_memory_check (uint32_t addr, int size, uint8_t *records)
uint64_t taintcheck_register_check (int reg, int offset, int size, uint8_t *records)
int taintcheck_taint_memory (uint32_t addr, int size, uint64_t taint, uint8_t *records)
int taintcheck_taint_register (int reg, int offset, int size, uint64_t taint, uint8_t *records)
void taintcheck_taint_virtmem (uint32_t vaddr, uint32_t size, uint64_t taint, void *records)
Function Documentation
void default_taint_propagate (int nr_src, taint_operand_t * src_oprnds, taint_operand_t * dst_oprnd, int mode)
This is the default taint_propagate implementation. For a Temu plugin, if it does not need to handle it specially, it can specify this function in its callback function definitions
Parameters:
nr_src Number of source operands
src_oprnds source operand array
dst_oprnd destination operand
mode propagation mode
Definition at line 1755 of file taintcheck.c.
References taint_operand_t::records, taint_operand_t::size, plugin_interface_t::taint_record_size, and temu_plugin.
uint64_t taintcheck_check_virtmem (uint32_t vaddr, uint32_t size, void * records)
Obtain taint information of a memory region by its virtual address
Parameters:
vaddr virtual address of memory region
size size of memory region
records the output buffer for storing taint records
Return values:
bitmap that indicates which bytes are tainted
Definition at line 1432 of file taintcheck.c.
References plugin_interface_t::taint_record_size, taintcheck_memory_check(), TEMU_get_phys_addr(), and temu_plugin.
int taintcheck_get_sizeof_taintmem ()
Get number of tainted bytes in the physcal memory
Return values:
number of tainted bytes
Definition at line 1186 of file taintcheck.c.
References disk_record::bitmap.
Referenced by do_info_taintmem().
uint64_t taintcheck_memory_check (uint32_t addr, int size, uint8_t * records)
Obtain taint information of a memory region by its physical address
Parameters:
addr physical address
size size of memory region
records the output buffer for storing taint records
Return values:
bitmap that indicates which bytes are tainted
Definition at line 1316 of file taintcheck.c.
References _tpage_entry::records, taint_mem_check(), plugin_interface_t::taint_record_size, TEMU_emulation_started, and temu_plugin.
Referenced by taintcheck_check_virtmem().
uint64_t taintcheck_register_check (int reg, int offset, int size, uint8_t * records)
Obtain taint information of a register
Parameters:
reg index of a full register, such as R_EAX, R_EBX
offset offset within a full register, e.g., AH has offset 1
size register size, e.g., the size of AX is 2
records output buffer for storing taint records
Return values:
bitmap that indicates which bytes are tainted
Definition at line 1344 of file taintcheck.c.
References regs_records, plugin_interface_t::taint_record_size, taint_reg_check(), TEMU_emulation_started, and temu_plugin.
int taintcheck_taint_memory (uint32_t addr, int size, uint64_t taint, uint8_t * records)
Set taint information of a memory region by its physical address
Parameters:
addr physical address of memory region
size size of memory region
taint bitmap that indicates which bytes are tainted
records user-specified buffer for storing taint records
Return values:
always 0
Taint a physical memory region: addr: physical address size: size of memory to taint (size <= 64) taint: bitmap of taint records: an array of taint records
Definition at line 1380 of file taintcheck.c.
References clean_memory(), _tpage_entry::records, taint_memory(), plugin_interface_t::taint_record_size, TEMU_emulation_started, and temu_plugin.
Referenced by taintcheck_taint_virtmem().
int taintcheck_taint_register (int reg, int offset, int size, uint64_t taint, uint8_t * records)
Set taint information of a register
Parameters:
reg index of a full register, such as R_EAX, R_EBX
offset offset within a full register, e.g., AH has offset 1
size register size, e.g., the size of AX is 2
taint bitmap that indicates which bytes are tainted
records user-specified buffer for storing taint records
Return values:
always 0
Definition at line 1359 of file taintcheck.c.
References regs_records, plugin_interface_t::taint_record_size, taint_register(), TEMU_emulation_started, and temu_plugin.
Referenced by taintcheck_nic_in().
void taintcheck_taint_virtmem (uint32_t vaddr, uint32_t size, uint64_t taint, void * records)
Set taint information of a memory region by its virtual address
Parameters:
vaddr virtual address of memory region
size size of memory region
taint bitmap that indicates which bytes are tainted
records user-specified buffer for storing taint records
Definition at line 1406 of file taintcheck.c.
References size_to_taint(), plugin_interface_t::taint_record_size, taintcheck_taint_memory(), TEMU_get_phys_addr(), and temu_plugin.
Referenced by _aligned_offset_malloc_call(), _aligned_offset_realloc_call(), calloc_call(), ExAllocatePoolWithTag_call(), ExInterlockedPushEntryList_call(), InterlockedPushEntrySList_call(), malloc_call(), NtAllocateVirtualMemory_call(), realloc_call(), RtlAllocateHeap_call(), and RtlReAllocateHeap_call().