TEMU: OS-Aware: OS-level Semantics Extractor
TEMU: Dynamic Binary Analysis Platform
OS-Aware: OS-level Semantics Extractor
Data Structures
struct _tmodinfo
Typedefs
typedef struct _tmodinfo tmodinfo_t
Functions
int find_process (uint32_t cr3, char proc[], uint32_t *pid)
uint32_t get_current_tid ()
tmodinfo_t * locate_module (uint32_t eip, uint32_t cr3, char proc[])
int procmod_insert_modinfo (uint32_t pid, uint32_t cr3, const char *name, uint32_t base, uint32_t size)
int update_proc (void *opaque)
Typedef Documentation
typedef struct _tmodinfo tmodinfo_t
a structure of module information
Function Documentation
int find_process (uint32_t cr3, char proc[], uint32_t * pid)
find process given a memory space id
Parameters:
cr3 memory space id: physical address of page table
proc process name (output argument)
pid process pid (output argument)
Returns:
number of modules in this process
Definition at line 360 of file procmod.cpp.
References process_info_t::cr3, process_info_t::module_list, process_info_t::name, process_info_t::pid, and process_list.
uint32_t get_current_tid ()
Returns:
the current thread id. If for some reason, this operation is not successful, the return value is set to -1. This function only works in Windows XP for Now.
Definition at line 517 of file procmod.cpp.
References is_guest_windows(), TEMU_cpu_segs, TEMU_is_in_kernel(), and TEMU_read_mem().
tmodinfo_t* locate_module (uint32_t eip, uint32_t cr3, char proc[])
locate the module that a given instruction belongs to
Parameters:
eip virtual address of a given instruction
cr3 memory space id: physical address of page table
proc process name (output argument)
Returns:
tmodinfo_t structure
int procmod_insert_modinfo (uint32_t pid, uint32_t cr3, const char * name, uint32_t base, uint32_t size)
This function inserts the module information
Definition at line 83 of file procmod.cpp.
References process_info_t::cr3, insert_module_info(), loadmainmodule_notify, process_info_t::module_list, process_info_t::name, process_info_t::pid, and process_list.
Referenced by parse_module(), and update_proc().
int update_proc (void * opaque)
This function is only used to update process and module information for Linux
Definition at line 185 of file procmod.cpp.
References get_first_mmap(), get_mod_name(), get_name(), get_next_mmap(), get_pgd(), get_pid(), get_vmend(), get_vmstart(), handle_message(), next_task_struct(), procmod_createproc(), procmod_insert_modinfo(), procmod_remove_all(), size, and taskaddr.
Referenced by detecting_kernel(), and do_linux_ps().