TEMU: hookapi.c File Reference
TEMU: Dynamic Binary Analysis Platform
hookapi.c File Reference
Data Structures
struct hookapi_handle
struct hookapi_record
Typedefs
typedef struct hookapi_handle hookapi_handle_t
typedef struct hookapi_record hookapi_record_t
Functions
void hookapi_check_call (int in_context)
void hookapi_cleanup ()
uintptr_t hookapi_hook_function (int is_global, uint32_t eip, hook_proc_t fnhook, void *opaque, uint32_t sizeof_opaque)
void hookapi_hook_function_byname (const char *mod_name, const char *fun_name, int is_global, hook_proc_t fnhook, void *opaque, uint32_t sizeof_opaque)
uintptr_t hookapi_hook_return (uint32_t eip, hook_proc_t fnhook, void *opaque, uint32_t sizeof_opaque)
static int hookapi_load (QEMUFile *f, void *opaque, int version_id)
static void hookapi_remove_all ()
void hookapi_remove_hook (uintptr_t handle)
static void hookapi_save (QEMUFile *f, void *opaque)
void init_hookapi ()
LIST_HEAD (hookapi_record_list_head, hookapi_record)
int register_hookapi (uint32_t eip, hook_proc_t fnhook, void *opaque, uint32_t sizeof_opaque)
int remove_hookapi (uint32_t eip)
Typedef Documentation
typedef struct hookapi_handle hookapi_handle_t
typedef struct hookapi_record hookapi_record_t
Function Documentation
void hookapi_cleanup ()
Definition at line 207 of file hookapi.c.
References deregister_savevm(), and hookapi_remove_all().
static int hookapi_load (QEMUFile * f, void * opaque, int version_id) [static]
Definition at line 127 of file hookapi.c.
References hookapi_record::cr3, hookapi_record::eip, hookapi_record::esp, hookapi_record::fnhook, hookapi_remove_all(), hookapi_record::is_global, hookapi_record::opaque, qemu_get_be32(), qemu_get_buffer(), qemu_get_byte(), and hookapi_record::sizeof_opaque.
Referenced by init_hookapi().
static void hookapi_remove_all () [static]
Definition at line 71 of file hookapi.c.
References hookapi_record::opaque.
Referenced by hookapi_cleanup(), and hookapi_load().
static void hookapi_save (QEMUFile * f, void * opaque) [static]
Definition at line 95 of file hookapi.c.
References hookapi_record::cr3, hookapi_record::eip, hookapi_record::esp, hookapi_record::fnhook, hookapi_record::is_global, hookapi_record::opaque, qemu_put_be32(), qemu_put_buffer(), qemu_put_byte(), and hookapi_record::sizeof_opaque.
Referenced by init_hookapi().
void init_hookapi ()
Definition at line 198 of file hookapi.c.
References hookapi_load(), hookapi_save(), and register_savevm().
LIST_HEAD (hookapi_record_list_head , hookapi_record)
Definition at line 51 of file hookapi.c.
References hookapi_handle::handle.
int register_hookapi (uint32_t eip, hook_proc_t fnhook, void * opaque, uint32_t sizeof_opaque)
Definition at line 214 of file hookapi.c.
int remove_hookapi (uint32_t eip)
Definition at line 314 of file hookapi.c.