TEMU: hookapi.h File Reference
TEMU: Dynamic Binary Analysis Platform
hookapi.h File Reference
Typedefs
typedef int(* hook_proc_t)(void *opaque)
Functions
void hookapi_check_call (int in_context)
void hookapi_cleanup ()
uintptr_t hookapi_hook_function (int is_global, uint32_t eip, hook_proc_t fnhook, void *opaque, uint32_t sizeof_opaque)
void hookapi_hook_function_byname (const char *mod, const char *func, int is_global, hook_proc_t fnhook, void *opaque, uint32_t sizeof_opaque)
uintptr_t hookapi_hook_return (uint32_t eip, hook_proc_t fnhook, void *opaque, uint32_t sizeof_opaque)
void hookapi_remove_hook (uintptr_t handle)
void init_hookapi ()
Typedef Documentation
typedef int(* hook_proc_t)(void *opaque)
Definition at line 27 of file hookapi.h.
Function Documentation
void hookapi_cleanup ()
Definition at line 207 of file hookapi.c.
References deregister_savevm(), and hookapi_remove_all().
void init_hookapi ()
Definition at line 198 of file hookapi.c.
References hookapi_load(), hookapi_save(), and register_savevm().