TEMU: junk.c File Reference
TEMU: Dynamic Binary Analysis Platform
junk.c File Reference
Functions
float detect_junk_insts (bfd_vma start, bfd_vma end)
unsigned char indep_regnum (unsigned char reg)
float inst_count_get (InstDigraphs *g, Instruction *i)
unsigned int inst_count_hash (unsigned char *o)
unsigned int inst_count_node_equals (InstDigraphNode *n, unsigned char *o)
void inst_count_put (InstDigraphs *g, unsigned char *o, unsigned int c)
void inst_digraph_destroy (InstDigraphs *g)
float inst_digraph_get (InstDigraphs *g, Instruction *i1, Instruction *i2)
unsigned int inst_digraph_hash (unsigned char *o1, unsigned char *o2)
void inst_digraph_incr (InstDigraphs *g, Instruction *i1, Instruction *i2)
void inst_digraph_init (InstDigraphs *g)
unsigned int inst_digraph_node_equals (InstDigraphNode *n, unsigned char *o1, unsigned char *o2)
void inst_digraph_parse (InstDigraphs *g, FILE *s)
void inst_digraph_print (InstDigraphs *g)
void inst_digraph_put (InstDigraphs *g, unsigned char *o1, unsigned char *o2, unsigned int c)
static int is_bad_instruction (Instruction *inst)
unsigned int is_div (Instruction *i)
unsigned int is_mov (Instruction *i)
unsigned int is_mul (Instruction *i)
unsigned int is_shift (Instruction *i)
unsigned int is_special_reg (Operand *o)
unsigned int is_uncommon_arithmetic (Instruction *i)
unsigned char op_width (Operand *op)
unsigned char reg_width (unsigned char reg)
float score_junk_insts (Instruction *last, Instruction *cur)
float update_junk_score (Instruction *newinst, Instruction *next, float orig, unsigned int num)
Variables
InstDigraphs digraphs
Function Documentation
float detect_junk_insts (bfd_vma start, bfd_vma end)
Detect if a given run of instructions is likely junk.
Parameters:
start Start position.
end End position.
Returns:
Instruction anomaly score. (0.0 valid, 1.0 junk)
Definition at line 671 of file junk.c.
References get_segment_of(), _segment::insts, i386_instruction::length, score_junk_insts(), and _segment::start_addr.
unsigned char indep_regnum (unsigned char reg)
Determine addressing-mode independent register number.
Parameters:
reg Register number.
Returns:
Mode-independent number.
Definition at line 378 of file junk.c.
Referenced by score_junk_insts().
float inst_count_get (InstDigraphs * g, Instruction * i)
Return probability of an instruction.
Parameters:
g Digraphs.
i Instruction.
Returns:
Probability.
Definition at line 176 of file junk.c.
References _inst_digraphs::count, _inst_digraph_node::count, _inst_digraphs::counts, hash(), inst_count_hash(), inst_count_node_equals(), _inst_digraph_node::next, and i386_instruction::opcode.
Referenced by score_junk_insts().
unsigned int inst_count_hash (unsigned char * o)
Instruction count hash function.
Parameters:
o Instruction opcodes.
Returns:
Hash value.
Definition at line 65 of file junk.c.
Referenced by inst_count_get(), inst_count_put(), inst_digraph_get(), and inst_digraph_incr().
unsigned int inst_count_node_equals (InstDigraphNode * n, unsigned char * o)
Determine if a count node is equal to an instruction.
Parameters:
n Count node.
o Instruction opcodes.
Returns:
True if equal, otherwise false.
Definition at line 80 of file junk.c.
References _inst_digraph_node::opcode.
Referenced by inst_count_get(), inst_count_put(), inst_digraph_get(), and inst_digraph_incr().
void inst_count_put (InstDigraphs * g, unsigned char * o, unsigned int c)
Put instruction count.
Parameters:
g Digraphs.
o Instruction opcodes.
c Count.
Definition at line 229 of file junk.c.
References _inst_digraph_node::count, _inst_digraphs::counts, fatal(), hash(), inst_count_hash(), inst_count_node_equals(), _inst_digraph_node::next, and _inst_digraph_node::opcode.
Referenced by inst_digraph_parse().
void inst_digraph_destroy (InstDigraphs * g)
Destroy instruction digraphs.
Parameters:
g Digraphs.
Definition at line 33 of file junk.c.
References _inst_digraphs::counts, _inst_digraphs::digraphs, and _inst_digraph_node::next.
float inst_digraph_get (InstDigraphs * g, Instruction * i1, Instruction * i2)
Return probability of an instruction digraph.
Parameters:
g Digraphs.
i1 Instruction 1.
i2 Instruction 2.
Returns:
Probability.
Definition at line 142 of file junk.c.
References _inst_digraph_node::count, _inst_digraphs::counts, _inst_digraphs::digraphs, fatal(), hash(), inst_count_hash(), inst_count_node_equals(), inst_digraph_hash(), inst_digraph_node_equals(), _inst_digraph_node::next, and i386_instruction::opcode.
Referenced by score_junk_insts().
unsigned int inst_digraph_hash (unsigned char * o1, unsigned char * o2)
Instruction digraph hash function.
Parameters:
o1 Instruction 1 opcodes.
o2 Instruction 2 opcodes.
Returns:
Hash value.
Definition at line 58 of file junk.c.
Referenced by inst_digraph_get(), inst_digraph_incr(), and inst_digraph_put().
void inst_digraph_incr (InstDigraphs * g, Instruction * i1, Instruction * i2)
Increment an instruction digraph count.
Parameters:
g Digraphs.
i1 Instruction 1.
i2 Instruction 2.
Definition at line 86 of file junk.c.
References _inst_digraphs::count, _inst_digraph_node::count, _inst_digraphs::counts, _inst_digraphs::digraphs, fatal(), hash(), inst_count_hash(), inst_count_node_equals(), inst_digraph_hash(), inst_digraph_node_equals(), _inst_digraph_node::next, _inst_digraph_node::opcode, and i386_instruction::opcode.
void inst_digraph_init (InstDigraphs * g)
Initialize instruction digraphs.
Parameters:
g Digraphs.
Definition at line 27 of file junk.c.
unsigned int inst_digraph_node_equals (InstDigraphNode * n, unsigned char * o1, unsigned char * o2)
Determine if a digraph node is equal to two instructions.
Parameters:
n Digraph node.
o1 Instruction 1 opcodes.
o2 Instruction 2 opcodes.
Returns:
True if equal, otherwise false.
Definition at line 72 of file junk.c.
References _inst_digraph_node::opcode.
Referenced by inst_digraph_get(), inst_digraph_incr(), and inst_digraph_put().
void inst_digraph_parse (InstDigraphs * g, FILE * s)
Parse serialized instruction digraphs.
Parameters:
g Digraphs.
s Input stream.
Definition at line 259 of file junk.c.
References _inst_digraphs::count, inst_count_put(), and inst_digraph_put().
void inst_digraph_print (InstDigraphs * g)
Print instruction digraphs.
Parameters:
g Digraphs.
Definition at line 347 of file junk.c.
References _inst_digraph_node::count, _inst_digraphs::count, _inst_digraphs::counts, _inst_digraphs::digraphs, _inst_digraph_node::next, and _inst_digraph_node::opcode.
void inst_digraph_put (InstDigraphs * g, unsigned char * o1, unsigned char * o2, unsigned int c)
Put count of instruction digraph.
Parameters:
g Digraphs.
o1 Instruction 1 opcodes.
o2 Instruction 2 opcodes.
c Count.
Definition at line 197 of file junk.c.
References _inst_digraph_node::count, _inst_digraphs::digraphs, fatal(), hash(), inst_digraph_hash(), inst_digraph_node_equals(), _inst_digraph_node::next, and _inst_digraph_node::opcode.
Referenced by inst_digraph_parse().
static int is_bad_instruction (Instruction * inst) [static]
Definition at line 519 of file junk.c.
References i386_op::bytemode1, fgrps, float_mem, float_reg, i386_group_1, i386_op_1, i386_op_2, i386_op::mnemonic, i386_instruction::modrm, onebyte_is_group, and i386_instruction::opcode.
Referenced by score_junk_insts().
unsigned int is_div (Instruction * i)
Determine if an instruction is a DIV instruction.
Parameters:
i Instruction.
Returns:
True if DIV, otherwise false.
Definition at line 462 of file junk.c.
References i386_instruction::opcode.
Referenced by is_uncommon_arithmetic().
unsigned int is_mov (Instruction * i)
Print error and exit. Determine if an instruction is a MOV instruction.
Parameters:
i Instruction.
Returns:
True if MOV, otherwise false.
Definition at line 437 of file junk.c.
References i386_instruction::opcode.
Referenced by score_junk_insts().
unsigned int is_mul (Instruction * i)
Determine if an instruction is a MUL instruction.
Parameters:
i Instruction.
Returns:
True if MUL, otherwise false.
Definition at line 451 of file junk.c.
References i386_instruction::opcode.
Referenced by is_uncommon_arithmetic().
unsigned int is_shift (Instruction * i)
Determine if an instruction is a SHx instruction.
Parameters:
i Instruction.
Returns:
True if SHx, otherwise false.
Definition at line 473 of file junk.c.
References i386_instruction::opcode.
Referenced by is_uncommon_arithmetic().
unsigned int is_special_reg (Operand * o)
Determine if a register is special-purpose.
Parameters:
o Operand.
Returns:
True if special register, otherwise false.
Definition at line 492 of file junk.c.
References _register::num, i386_operand::i386_operand::OpValue::reg, and i386_operand::value.
Referenced by score_junk_insts().
unsigned int is_uncommon_arithmetic (Instruction * i)
Determine if an instruction is a less common arithmetic instruction.
Parameters:
i Instruction.
Returns:
True if less common arithmetic instruction, otherwise false.
Definition at line 484 of file junk.c.
References is_div(), is_mul(), and is_shift().
Referenced by score_junk_insts().
unsigned char op_width (Operand * op)
Determine width of operand.
Parameters:
op Operand.
Returns:
Width as addressing mode.
Definition at line 404 of file junk.c.
References fatal(), i386_operand::i386_operand::OpValue::freg, i386_operand::i386_operand::OpValue::imm, i386_operand::i386_operand::OpValue::jmp, _float_register::num, _register::num, i386_operand::i386_operand::OpValue::reg, reg_width(), TFloatRegister, TImmediate, TJump, TMemLoc, TRegister, _jump::type, _immediate::type, i386_operand::type, and i386_operand::value.
Referenced by score_junk_insts().
unsigned char reg_width (unsigned char reg)
Determine width of register.
Parameters:
reg Register number.
Returns:
Register width as addressing mode.
Definition at line 391 of file junk.c.
Referenced by op_width().
float score_junk_insts (Instruction * last, Instruction * cur)
Return a junk score for two instructions.
Parameters:
last Last instruction.
cur Current instruction.
Returns:
Junk instruction score.
Definition at line 565 of file junk.c.
References _mem_loc::base, indep_regnum(), inst_count_get(), inst_digraph_get(), is_bad_instruction(), is_mov(), is_special_reg(), is_uncommon_arithmetic(), i386_instruction::length, i386_operand::i386_operand::OpValue::mem, i386_instruction::modrm, _register::num, op_width(), i386_instruction::opcode, i386_instruction::ops, i386_operand::i386_operand::OpValue::reg, TMemLoc, TNone, TRegister, i386_operand::type, and i386_operand::value.
Referenced by detect_junk_insts(), and update_junk_score().
float update_junk_score (Instruction * newinstr, Instruction * next, float orig, unsigned int num)
Update a previously-computed junk instruction score taking into account a new instruction which prefaces the previous run.
Parameters:
new New instruction.
next Next instruction.
orig Original score.
num Length of original run.
Returns:
Updated junk score.
Definition at line 652 of file junk.c.
References score_junk_insts().
Variable Documentation
InstDigraphs digraphs
Instruction digraphs
Definition at line 24 of file junk.c.