TEMU: procmod.h File Reference
TEMU: Dynamic Binary Analysis Platform
procmod.h File Reference
Data Structures
struct _old_tmodinfo
struct _tmodinfo
Typedefs
typedef void(* createproc_notify_t)(uint32_t pid, uint32_t cr3)
typedef void(* loadmainmodule_notify_t)(uint32_t pid, char *name)
typedef void(* loadmodule_notify_t)(uint32_t pid, uint32_t cr3, char *name, uint32_t base, uint32_t size)
typedef struct _old_tmodinfo old_modinfo_t
typedef void(* removeproc_notify_t)(uint32_t pid)
typedef struct _tmodinfo tmodinfo_t
Functions
int checkcr3 (uint32_t cr3, uint32_t eip, uint32_t tracepid, char *name, int len, uint32_t *offset)
void do_linux_ps ()
uint32_t find_cr3 (uint32_t pid)
uint32_t find_pid (uint32_t cr3)
uint32_t find_pid_by_name (const char *proc_name)
int find_process (uint32_t cr3, char proc[], uint32_t *pid)
uint32_t get_current_tid ()
void get_proc_modules (uint32_t pid, old_modinfo_t *buf, int size)
int is_guest_windows ()
void list_guest_modules (uint32_t pid)
void list_procs ()
tmodinfo_t * locate_module (uint32_t eip, uint32_t cr3, char proc[])
tmodinfo_t * locate_module_byname (const char *name, uint32_t pid)
void parse_module (char *log)
void parse_process (char *log)
void procmod_cleanup ()
int procmod_init ()
int procmod_insert_modinfo (uint32_t pid, uint32_t cr3, const char *name, uint32_t base, uint32_t size)
int update_proc (void *opaque)
Variables
createproc_notify_t createproc_notify
loadmainmodule_notify_t loadmainmodule_notify
loadmodule_notify_t loadmodule_notify
removeproc_notify_t removeproc_notify
Typedef Documentation
typedef void(* createproc_notify_t)(uint32_t pid, uint32_t cr3)
Definition at line 40 of file procmod.h.
typedef void(* loadmainmodule_notify_t)(uint32_t pid, char *name)
Definition at line 49 of file procmod.h.
typedef void(* loadmodule_notify_t)(uint32_t pid, uint32_t cr3, char *name, uint32_t base, uint32_t size)
Definition at line 42 of file procmod.h.
typedef struct _old_tmodinfo old_modinfo_t
typedef void(* removeproc_notify_t)(uint32_t pid)
Definition at line 41 of file procmod.h.
Function Documentation
int checkcr3 (uint32_t cr3, uint32_t eip, uint32_t tracepid, char * name, int len, uint32_t * offset)
Definition at line 487 of file procmod.cpp.
References module_info_t::base, process_info_t::cr3, process_info_t::module_list, module_info_t::name, process_info_t::pid, process_list, and module_info_t::size.
void do_linux_ps ()
Definition at line 394 of file procmod.cpp.
References get_first_mmap(), get_mod_name(), get_name(), get_next_mmap(), get_pgd(), get_pid(), get_vmend(), get_vmstart(), init_kernel_offsets(), next_task_struct(), taskaddr, term_printf(), and update_proc().
uint32_t find_cr3 (uint32_t pid)
Definition at line 429 of file procmod.cpp.
References process_info_t::cr3, process_info_t::pid, and process_list.
uint32_t find_pid (uint32_t cr3)
Definition at line 332 of file procmod.cpp.
References process_info_t::cr3, process_info_t::pid, and process_list.
uint32_t find_pid_by_name (const char * proc_name)
Definition at line 345 of file procmod.cpp.
References process_info_t::name, process_info_t::pid, and process_list.
void get_proc_modules (uint32_t pid, old_modinfo_t * buf, int size)
int is_guest_windows ()
Definition at line 707 of file procmod.cpp.
References TEMU_cpu_segs.
Referenced by get_current_tid().
void list_guest_modules (uint32_t pid)
Definition at line 467 of file procmod.cpp.
References module_info_t::base, process_info_t::cr3, process_info_t::module_list, module_info_t::name, process_info_t::pid, process_list, module_info_t::size, and term_printf().
void list_procs ()
Definition at line 381 of file procmod.cpp.
References process_info_t::cr3, process_info_t::name, process_info_t::pid, process_list, and term_printf().
tmodinfo_t* locate_module_byname (const char * name, uint32_t pid)
Definition at line 319 of file procmod.cpp.
References find_module_byname(), process_info_t::module_list, process_info_t::pid, and process_list.
void parse_module (char * log)
Definition at line 688 of file procmod.cpp.
References loadmodule_notify, procmod_insert_modinfo(), and size.
Referenced by procmod_init().
void parse_process (char * log)
Definition at line 671 of file procmod.cpp.
References procmod_createproc(), and procmod_removeproc().
Referenced by procmod_init().
void procmod_cleanup ()
Definition at line 245 of file procmod.cpp.
References deregister_savevm(), and procmod_remove_all().
int procmod_init ()
Definition at line 636 of file procmod.cpp.
References detecting_kernel(), for_all_hookpoints(), guestlog, handle_message(), parse_module(), parse_process(), procmod_createproc(), procmod_load(), procmod_save(), and register_savevm().
Variable Documentation
createproc_notify_t createproc_notify
Definition at line 47 of file procmod.cpp.
Referenced by procmod_createproc().
loadmainmodule_notify_t loadmainmodule_notify
Definition at line 52 of file procmod.cpp.
Referenced by procmod_insert_modinfo().
loadmodule_notify_t loadmodule_notify
Definition at line 49 of file procmod.cpp.
Referenced by parse_module().
removeproc_notify_t removeproc_notify
Definition at line 48 of file procmod.cpp.
Referenced by procmod_removeproc().