TEMU: procmod.cpp File Reference
TEMU: Dynamic Binary Analysis Platform
procmod.cpp File Reference
Data Structures
struct module_info_t
struct process_info_t
Functions
int checkcr3 (uint32_t cr3, uint32_t eip, uint32_t tracepid, char *name, int len, uint32_t *offset)
int detecting_kernel (void *opaque)
void do_linux_ps ()
uint32_t find_cr3 (uint32_t pid)
static tmodinfo_t * find_module_byeip (uint32_t eip, list< module_info_t * > &module_list)
static tmodinfo_t * find_module_byname (const char *name, list< module_info_t * > &module_list)
uint32_t find_pid (uint32_t cr3)
uint32_t find_pid_by_name (const char *proc_name)
int find_process (uint32_t cr3, char proc_name[], uint32_t *pid)
uint32_t get_current_tid ()
void get_proc_modules (uint32_t pid, old_modinfo_t mi_array[], int size)
int insert_module_info (list< module_info_t * > &module_list, const char *name, uint32_t base, uint32_t size)
int is_guest_windows ()
void list_guest_modules (uint32_t pid)
void list_procs ()
tmodinfo_t * locate_module (uint32_t eip, uint32_t cr3, char *proc_name)
tmodinfo_t * locate_module_byname (const char *name, uint32_t pid)
void parse_module (char *log)
void parse_process (char *log)
void procmod_cleanup ()
int procmod_createproc (uint32_t pid, uint32_t cr3, const char *name)
int procmod_init ()
int procmod_insert_modinfo (uint32_t pid, uint32_t cr3, const char *name, uint32_t base, uint32_t size)
static int procmod_load (QEMUFile *f, void *opaque, int version_id)
static int procmod_remove_all ()
int procmod_removeproc (uint32_t pid)
static void procmod_save (QEMUFile *f, void *opaque)
int update_proc (void *opaque)
Variables
createproc_notify_t createproc_notify = NULL
loadmainmodule_notify_t loadmainmodule_notify = NULL
loadmodule_notify_t loadmodule_notify = NULL
static list< process_info_t * > process_list
removeproc_notify_t removeproc_notify = NULL
Function Documentation
int checkcr3 (uint32_t cr3, uint32_t eip, uint32_t tracepid, char * name, int len, uint32_t * offset)
Definition at line 487 of file procmod.cpp.
References module_info_t::base, process_info_t::cr3, process_info_t::module_list, module_info_t::name, process_info_t::pid, process_list, and module_info_t::size.
int detecting_kernel (void * opaque)
Definition at line 623 of file procmod.cpp.
References for_all_hookpoints(), hookapi_hook_function(), hookingpoint, init_kernel_offsets(), and update_proc().
Referenced by procmod_init().
void do_linux_ps ()
Definition at line 394 of file procmod.cpp.
References get_first_mmap(), get_mod_name(), get_name(), get_next_mmap(), get_pgd(), get_pid(), get_vmend(), get_vmstart(), init_kernel_offsets(), next_task_struct(), taskaddr, term_printf(), and update_proc().
uint32_t find_cr3 (uint32_t pid)
Definition at line 429 of file procmod.cpp.
References process_info_t::cr3, process_info_t::pid, and process_list.
static tmodinfo_t* find_module_byeip (uint32_t eip, list< module_info_t * > & module_list) [static]
Definition at line 254 of file procmod.cpp.
References _tmodinfo::base, module_info_t::base, module_info_t::name, _tmodinfo::name, _tmodinfo::size, and module_info_t::size.
Referenced by locate_module().
static tmodinfo_t* find_module_byname (const char * name, list< module_info_t * > & module_list) [static]
Definition at line 276 of file procmod.cpp.
References module_info_t::base, _tmodinfo::base, _tmodinfo::name, module_info_t::name, module_info_t::size, and _tmodinfo::size.
Referenced by locate_module_byname().
uint32_t find_pid (uint32_t cr3)
Definition at line 332 of file procmod.cpp.
References process_info_t::cr3, process_info_t::pid, and process_list.
uint32_t find_pid_by_name (const char * proc_name)
Definition at line 345 of file procmod.cpp.
References process_info_t::name, process_info_t::pid, and process_list.
void get_proc_modules (uint32_t pid, old_modinfo_t mi_array[], int size)
Definition at line 444 of file procmod.cpp.
References module_info_t::base, _old_tmodinfo::base, process_info_t::module_list, _old_tmodinfo::name, module_info_t::name, process_info_t::pid, process_list, module_info_t::size, and _old_tmodinfo::size.
int insert_module_info (list< module_info_t * > & module_list, const char * name, uint32_t base, uint32_t size)
Definition at line 54 of file procmod.cpp.
References module_info_t::base, module_info_t::name, and module_info_t::size.
Referenced by procmod_insert_modinfo(), and procmod_load().
int is_guest_windows ()
Definition at line 707 of file procmod.cpp.
References TEMU_cpu_segs.
Referenced by get_current_tid().
void list_guest_modules (uint32_t pid)
Definition at line 467 of file procmod.cpp.
References module_info_t::base, process_info_t::cr3, process_info_t::module_list, module_info_t::name, process_info_t::pid, process_list, module_info_t::size, and term_printf().
void list_procs ()
Definition at line 381 of file procmod.cpp.
References process_info_t::cr3, process_info_t::name, process_info_t::pid, process_list, and term_printf().
tmodinfo_t* locate_module (uint32_t eip, uint32_t cr3, char * proc_name)
Definition at line 296 of file procmod.cpp.
References process_info_t::cr3, find_module_byeip(), process_info_t::module_list, process_info_t::name, and process_list.
tmodinfo_t* locate_module_byname (const char * name, uint32_t pid)
Definition at line 319 of file procmod.cpp.
References find_module_byname(), process_info_t::module_list, process_info_t::pid, and process_list.
void parse_module (char * log)
Definition at line 688 of file procmod.cpp.
References loadmodule_notify, procmod_insert_modinfo(), and size.
Referenced by procmod_init().
void parse_process (char * log)
Definition at line 671 of file procmod.cpp.
References procmod_createproc(), and procmod_removeproc().
Referenced by procmod_init().
void procmod_cleanup ()
Definition at line 245 of file procmod.cpp.
References deregister_savevm(), and procmod_remove_all().
int procmod_createproc (uint32_t pid, uint32_t cr3, const char * name)
Definition at line 114 of file procmod.cpp.
References process_info_t::cr3, createproc_notify, process_info_t::name, process_info_t::pid, and process_list.
Referenced by parse_process(), procmod_init(), and update_proc().
int procmod_init ()
Definition at line 636 of file procmod.cpp.
References detecting_kernel(), for_all_hookpoints(), guestlog, handle_message(), parse_module(), parse_process(), procmod_createproc(), procmod_load(), procmod_save(), and register_savevm().
static int procmod_load (QEMUFile * f, void * opaque, int version_id) [static]
Definition at line 576 of file procmod.cpp.
References process_info_t::cr3, insert_module_info(), process_info_t::module_list, process_info_t::name, process_info_t::pid, process_list, procmod_remove_all(), qemu_get_be32(), qemu_get_buffer(), and size.
Referenced by procmod_init().
static int procmod_remove_all () [static]
Definition at line 165 of file procmod.cpp.
References process_info_t::module_list, and process_list.
Referenced by procmod_cleanup(), procmod_load(), and update_proc().
int procmod_removeproc (uint32_t pid)
Definition at line 137 of file procmod.cpp.
References process_info_t::module_list, process_info_t::pid, process_list, and removeproc_notify.
Referenced by parse_process().
static void procmod_save (QEMUFile * f, void * opaque) [static]
Definition at line 541 of file procmod.cpp.
References module_info_t::base, process_info_t::cr3, process_info_t::module_list, module_info_t::name, process_info_t::name, process_info_t::pid, process_list, qemu_put_be32(), qemu_put_buffer(), and module_info_t::size.
Referenced by procmod_init().
Variable Documentation
createproc_notify_t createproc_notify = NULL
Definition at line 47 of file procmod.cpp.
Referenced by procmod_createproc().
loadmainmodule_notify_t loadmainmodule_notify = NULL
Definition at line 52 of file procmod.cpp.
Referenced by procmod_insert_modinfo().
loadmodule_notify_t loadmodule_notify = NULL
Definition at line 49 of file procmod.cpp.
Referenced by parse_module().
list<process_info_t *> process_list [static]
Definition at line 45 of file procmod.cpp.
Referenced by checkcr3(), find_cr3(), find_pid(), find_pid_by_name(), find_process(), get_proc_modules(), list_guest_modules(), list_procs(), locate_module(), locate_module_byname(), procmod_createproc(), procmod_insert_modinfo(), procmod_load(), procmod_remove_all(), procmod_removeproc(), and procmod_save().
removeproc_notify_t removeproc_notify = NULL
Definition at line 48 of file procmod.cpp.
Referenced by procmod_removeproc().