TEMU: read_linux.c File Reference
TEMU: Dynamic Binary Analysis Platform
read_linux.c File Reference
Functions
void for_all_hookpoints (hook_proc_t func, int action)
target_ulong get_first_mmap (target_ulong addr)
void get_mod_name (target_ulong addr, char *name, int size)
void get_name (target_ulong addr, char *buf, int size)
target_ulong get_next_mmap (target_ulong addr)
target_ulong get_pgd (target_ulong addr)
target_ulong get_pid (target_ulong addr)
target_ulong get_vmend (target_ulong addr)
target_ulong get_vmstart (target_ulong addr)
int init_kernel_offsets ()
target_ulong next_task_struct (target_ulong addr)
Variables
int commoffset = 0
int commsize = 0
int dentryoffset = 0
int dinameoffset = 0
int dnameoffset = 0
static uint32_t hook_handles [sizeof(kernel_table)/sizeof(struct koffset)]
target_ulong hookingpoint = 0
target_ulong hookingpoint2 = 0
target_ulong kernel_mem_start = 0x80000000
static struct koffset kernel_table []
int listoffset = 0
int mmoffset = 0
int pgdoffset = 0
int pidoffset = 0
target_ulong taskaddr = 0
int tasksize = 0
int vmendoffset = 0
int vmfileoffset = 0
int vmnextoffset = 0
int vmstartoffset = 0
Function Documentation
void for_all_hookpoints (hook_proc_t func, int action)
Definition at line 344 of file read_linux.c.
References hook_handles, hookapi_hook_function(), hookapi_remove_hook(), hookingpoint, and koffset::version.
Referenced by detecting_kernel(), and procmod_init().
target_ulong get_first_mmap (target_ulong addr)
Definition at line 254 of file read_linux.c.
References mmoffset, and TEMU_read_mem().
Referenced by do_linux_ps(), and update_proc().
void get_mod_name (target_ulong addr, char * name, int size)
Definition at line 291 of file read_linux.c.
References dentryoffset, dinameoffset, TEMU_memory_rw(), and vmfileoffset.
Referenced by do_linux_ps(), and update_proc().
void get_name (target_ulong addr, char * buf, int size)
Definition at line 248 of file read_linux.c.
References commoffset, commsize, and TEMU_read_mem().
Referenced by do_linux_ps(), and update_proc().
target_ulong get_next_mmap (target_ulong addr)
Definition at line 270 of file read_linux.c.
References TEMU_read_mem(), and vmnextoffset.
Referenced by do_linux_ps(), and update_proc().
target_ulong get_pgd (target_ulong addr)
Definition at line 232 of file read_linux.c.
References mmoffset, pgdoffset, and TEMU_read_mem().
Referenced by do_linux_ps(), and update_proc().
target_ulong get_pid (target_ulong addr)
Definition at line 223 of file read_linux.c.
References pidoffset, and TEMU_read_mem().
Referenced by do_linux_ps(), and update_proc().
target_ulong get_vmend (target_ulong addr)
Definition at line 284 of file read_linux.c.
References TEMU_read_mem(), and vmendoffset.
Referenced by do_linux_ps(), and update_proc().
target_ulong get_vmstart (target_ulong addr)
Definition at line 277 of file read_linux.c.
References TEMU_read_mem(), and vmstartoffset.
Referenced by do_linux_ps(), and update_proc().
int init_kernel_offsets ()
Definition at line 302 of file read_linux.c.
References koffset::commoffset, commoffset, koffset::commsize, commsize, koffset::dentryoffset, dentryoffset, koffset::dinameoffset, dinameoffset, koffset::dnameoffset, dnameoffset, koffset::hookingpoint, hookingpoint, koffset::hookingpoint2, hookingpoint2, kernel_mem_start, koffset::listoffset, listoffset, koffset::mmoffset, mmoffset, koffset::pgdoffset, pgdoffset, koffset::pidoffset, pidoffset, koffset::taskaddr, taskaddr, koffset::tasksize, tasksize, TEMU_memory_rw(), koffset::version, koffset::vmendoffset, vmendoffset, koffset::vmfileoffset, vmfileoffset, koffset::vmnextoffset, vmnextoffset, koffset::vmstartoffset, and vmstartoffset.
Referenced by detecting_kernel(), and do_linux_ps().
target_ulong next_task_struct (target_ulong addr)
Definition at line 204 of file read_linux.c.
References listoffset, taskaddr, and TEMU_read_mem().
Referenced by do_linux_ps(), and update_proc().
Variable Documentation
int commoffset = 0
Definition at line 37 of file read_linux.c.
Referenced by get_name(), and init_kernel_offsets().
int commsize = 0
Definition at line 38 of file read_linux.c.
Referenced by get_name(), and init_kernel_offsets().
int dentryoffset = 0
Definition at line 43 of file read_linux.c.
Referenced by get_mod_name(), and init_kernel_offsets().
int dinameoffset = 0
Definition at line 45 of file read_linux.c.
Referenced by get_mod_name(), and init_kernel_offsets().
int dnameoffset = 0
Definition at line 44 of file read_linux.c.
Referenced by init_kernel_offsets().
uint32_t hook_handles[sizeof(kernel_table)/sizeof(struct koffset)] [static]
Definition at line 342 of file read_linux.c.
Referenced by for_all_hookpoints().
target_ulong hookingpoint = 0
Definition at line 29 of file read_linux.c.
Referenced by detecting_kernel(), for_all_hookpoints(), and init_kernel_offsets().
target_ulong hookingpoint2 = 0
Definition at line 30 of file read_linux.c.
Referenced by init_kernel_offsets().
target_ulong kernel_mem_start = 0x80000000
Definition at line 27 of file read_linux.c.
Referenced by init_kernel_offsets().
struct koffset kernel_table[] [static]
Definition at line 51 of file read_linux.c.
int listoffset = 0
Definition at line 33 of file read_linux.c.
Referenced by init_kernel_offsets(), and next_task_struct().
int mmoffset = 0
Definition at line 35 of file read_linux.c.
Referenced by get_first_mmap(), get_pgd(), and init_kernel_offsets().
int pgdoffset = 0
Definition at line 36 of file read_linux.c.
Referenced by get_pgd(), and init_kernel_offsets().
int pidoffset = 0
Definition at line 34 of file read_linux.c.
Referenced by get_pid(), and init_kernel_offsets().
target_ulong taskaddr = 0
Definition at line 31 of file read_linux.c.
Referenced by do_linux_ps(), init_kernel_offsets(), next_task_struct(), and update_proc().
int tasksize = 0
Definition at line 32 of file read_linux.c.
Referenced by init_kernel_offsets().
int vmendoffset = 0
Definition at line 40 of file read_linux.c.
Referenced by get_vmend(), and init_kernel_offsets().
int vmfileoffset = 0
Definition at line 42 of file read_linux.c.
Referenced by get_mod_name(), and init_kernel_offsets().
int vmnextoffset = 0
Definition at line 41 of file read_linux.c.
Referenced by get_next_mmap(), and init_kernel_offsets().
int vmstartoffset = 0
Definition at line 39 of file read_linux.c.
Referenced by get_vmstart(), and init_kernel_offsets().