TEMU: reduce_taint.h File Reference
TEMU: Dynamic Binary Analysis Platform
reduce_taint.h File Reference
Functions
void reduce_taint_init ()
Function Documentation
void reduce_taint_init ()
Definition at line 125 of file reduce_taint.c.
References _aligned_offset_malloc_call(), _aligned_offset_realloc_call(), alloca_probe_call(), calloc_call(), ExAllocatePoolWithTag_call(), ExInterlockedPushEntryList_call(), hookapi_hook_function_byname(), InterlockedPushEntrySList_call(), malloc_call(), NtAllocateVirtualMemory_call(), realloc_call(), RtlAllocateHeap_call(), and RtlReAllocateHeap_call().