TEMU: reduce_taint.c File Reference
TEMU: Dynamic Binary Analysis Platform
reduce_taint.c File Reference
Functions
static int _aligned_offset_malloc_call (void *opaque)
static int _aligned_offset_realloc_call (void *opaque)
static int alloca_probe_call (void *opaque)
static int alloca_probe_ret (void *opaque)
static int calloc_call (void *opaque)
static int ExAllocatePoolWithTag_call (void *opaque)
static int ExInterlockedPushEntryList_call (void *opaque)
static int InterlockedPushEntrySList_call (void *opaque)
static int malloc_call (void *opaque)
static int NtAllocateVirtualMemory_call (void *opaque)
static int realloc_call (void *opaque)
void reduce_taint_init ()
static int RtlAllocateHeap_call (void *opaque)
static int RtlReAllocateHeap_call (void *opaque)
Function Documentation
static int _aligned_offset_malloc_call (void * opaque) [static]
Definition at line 89 of file reduce_taint.c.
References taintcheck_taint_virtmem(), and TEMU_cpu_regs.
Referenced by reduce_taint_init().
static int _aligned_offset_realloc_call (void * opaque) [static]
Definition at line 95 of file reduce_taint.c.
References taintcheck_taint_virtmem(), and TEMU_cpu_regs.
Referenced by reduce_taint_init().
static int alloca_probe_call (void * opaque) [static]
Definition at line 77 of file reduce_taint.c.
References alloca_probe_ret(), hookapi_hook_return(), TEMU_cpu_regs, and TEMU_read_mem().
Referenced by reduce_taint_init().
static int alloca_probe_ret (void * opaque) [static]
Definition at line 68 of file reduce_taint.c.
References hookapi_remove_hook(), and taintcheck_reg_clean().
Referenced by alloca_probe_call().
static int calloc_call (void * opaque) [static]
Definition at line 101 of file reduce_taint.c.
References taintcheck_taint_virtmem(), and TEMU_cpu_regs.
Referenced by reduce_taint_init().
static int ExAllocatePoolWithTag_call (void * opaque) [static]
Definition at line 26 of file reduce_taint.c.
References taintcheck_taint_virtmem(), and TEMU_cpu_regs.
Referenced by reduce_taint_init().
static int ExInterlockedPushEntryList_call (void * opaque) [static]
Definition at line 44 of file reduce_taint.c.
References taintcheck_taint_virtmem(), TEMU_cpu_regs, and TEMU_read_mem().
Referenced by reduce_taint_init().
static int InterlockedPushEntrySList_call (void * opaque) [static]
Definition at line 55 of file reduce_taint.c.
References taintcheck_reg_clean(), taintcheck_taint_virtmem(), TEMU_cpu_regs, and TEMU_read_mem().
Referenced by reduce_taint_init().
static int malloc_call (void * opaque) [static]
Definition at line 107 of file reduce_taint.c.
References taintcheck_taint_virtmem(), and TEMU_cpu_regs.
Referenced by reduce_taint_init().
static int NtAllocateVirtualMemory_call (void * opaque) [static]
Definition at line 119 of file reduce_taint.c.
References taintcheck_taint_virtmem(), and TEMU_cpu_regs.
Referenced by reduce_taint_init().
static int realloc_call (void * opaque) [static]
Definition at line 113 of file reduce_taint.c.
References taintcheck_taint_virtmem(), and TEMU_cpu_regs.
Referenced by reduce_taint_init().
void reduce_taint_init ()
Definition at line 125 of file reduce_taint.c.
References _aligned_offset_malloc_call(), _aligned_offset_realloc_call(), alloca_probe_call(), calloc_call(), ExAllocatePoolWithTag_call(), ExInterlockedPushEntryList_call(), hookapi_hook_function_byname(), InterlockedPushEntrySList_call(), malloc_call(), NtAllocateVirtualMemory_call(), realloc_call(), RtlAllocateHeap_call(), and RtlReAllocateHeap_call().
static int RtlAllocateHeap_call (void * opaque) [static]
Definition at line 32 of file reduce_taint.c.
References taintcheck_taint_virtmem(), and TEMU_cpu_regs.
Referenced by reduce_taint_init().
static int RtlReAllocateHeap_call (void * opaque) [static]
Definition at line 38 of file reduce_taint.c.
References taintcheck_taint_virtmem(), and TEMU_cpu_regs.
Referenced by reduce_taint_init().