TEMU: plugin_interface_t Struct Reference
TEMU: Dynamic Binary Analysis Platform
plugin_interface_t Struct Reference
[temu: Main TEMU Module]
primary structure for TEMU plugin, including callbacks and states
#include <TEMU_main.h>
Data Fields
void(* after_iret_protected)()
This callback indicates an interrupt is returned.
void(* after_loadvm)(const char *param)
void(* bdrv_open)(int index, void *opaque)
int(* block_begin)()
This callback is invoked at the beginning of each basic block.
void(* block_end)()
This callback is invoked at the end of each basic block.
void(* call_analysis)(uint32_t next_eip)
int(* cheat_sidt)()
int(* cjmp)(uint32_t t0)
void(* do_interrupt)(int intno, int is_int, uint32_t next_eip)
This callback indicates an interrupt is happening.
void(* eip_tainted)(uint8_t *record)
void(* guest_message)(char *message)
This callback handles OS-level semantics information.
term_cmd_t * info_cmds
array of informational commands
void(* insn_begin)()
This callback is invoked at the beginning of each instruction.
void(* insn_end)()
This callback is invoked at the end of each instruction.
void(* mem_read)(uint32_t virt_addr, uint32_t phys_addr, int size)
This callback is invoked when the current instruction reads a memory region.
void(* mem_write)(uint32_t virt_addr, uint32_t phys_addr, int size)
This callback is invoked when the current instruction writes a memory region.
void(* memreg_eip_change)()
uint32_t monitored_cr3
CR3 of a specified process to be monitored. 0 means system-wide monitoring, including all processes and kernel.
void(* nic_recv)(uint8_t *buf, int size, int cur_pos, int start, int stop)
This callback is invoked when a network packet is received by NIC.
void(* nic_send)(uint32_t addr, int size, uint8_t *buf)
This callback is invoked when a network packet is sent out by NIC.
void(* plugin_cleanup)()
callback for cleaning up states in plugin. TEMU plugin must release all allocated resources in this function
void(* pre_mem_write)(uint32_t virt_addr, uint32_t phys_addr, int size)
void(* read_disk_taint)(uint64_t addr, uint8_t *record, void *opaque)
void(* reg_read)(uint32_t regidx, int size)
This callback is invoked when the current instruction reads a register.
void(* reg_write)(uint32_t regidx, int size)
This callback is invoked when the current instruction writes a register.
void(* send_keystroke)(int reg)
void(* taint_disk)(uint64_t addr, uint8_t *record, void *opaque)
void(* taint_propagate)(int nr_src, taint_operand_t *src_oprnds, taint_operand_t *dst_oprnd, int mode)
This callback customizes its own policy for taint propagation.
int taint_record_size
size of taint record for each tainted byte. TEMU sees taint record as untyped buffer, so it only cares about the size of taint record
term_cmd_t * term_cmds
array of terminal commands
Detailed Description
primary structure for TEMU plugin, including callbacks and states
Definition at line 293 of file TEMU_main.h.
Field Documentation
void(* plugin_interface_t::after_iret_protected)()
This callback indicates an interrupt is returned.
Referenced by TEMU_after_iret_protected().
void(* plugin_interface_t::after_loadvm)(const char *param)
Referenced by TEMU_after_loadvm().
void(* plugin_interface_t::bdrv_open)(int index, void *opaque)
Referenced by do_load_plugin().
int(* plugin_interface_t::block_begin)()
This callback is invoked at the beginning of each basic block.
Referenced by TEMU_block_begin().
void(* plugin_interface_t::block_end)()
This callback is invoked at the end of each basic block.
Referenced by TEMU_block_end().
void(* plugin_interface_t::call_analysis)(uint32_t next_eip)
Referenced by TEMU_call_analysis().
int(* plugin_interface_t::cheat_sidt)()
Referenced by taintcheck_sidt().
int(* plugin_interface_t::cjmp)(uint32_t t0)
Referenced by taintcheck_jnz_T0_label().
void(* plugin_interface_t::do_interrupt)(int intno, int is_int, uint32_t next_eip)
This callback indicates an interrupt is happening.
Parameters:
intno interrupt number
is_int is it software interrupt?
next_eip EIP value when interrupt returns
Referenced by TEMU_do_interrupt().
void(* plugin_interface_t::eip_tainted)(uint8_t *record)
Referenced by taintcheck_check_eip().
void(* plugin_interface_t::guest_message)(char *message)
This callback handles OS-level semantics information.
It needs to parse the message and maintain process, module, and function information, using functionality in OS-Aware: OS-level Semantics Extractor.
Referenced by TEMU_virtdev_write_data().
term_cmd_t* plugin_interface_t::info_cmds
array of informational commands
Definition at line 297 of file TEMU_main.h.
void(* plugin_interface_t::insn_begin)()
This callback is invoked at the beginning of each instruction.
Referenced by TEMU_insn_begin().
void(* plugin_interface_t::insn_end)()
This callback is invoked at the end of each instruction.
Referenced by TEMU_insn_end().
void(* plugin_interface_t::mem_read)(uint32_t virt_addr, uint32_t phys_addr, int size)
This callback is invoked when the current instruction reads a memory region.
Parameters:
virt_addr virtual address of memory region
phys_addr physical address of memory region
size size of memory region
void(* plugin_interface_t::mem_write)(uint32_t virt_addr, uint32_t phys_addr, int size)
This callback is invoked when the current instruction writes a memory region.
Parameters:
virt_addr virtual address of memory region
phys_addr physical address of memory region
size size of memory region
Referenced by __attribute__().
void(* plugin_interface_t::memreg_eip_change)()
Referenced by taintcheck_check_eip().
uint32_t plugin_interface_t::monitored_cr3
CR3 of a specified process to be monitored. 0 means system-wide monitoring, including all processes and kernel.
Definition at line 371 of file TEMU_main.h.
Referenced by TEMU_update_cr3().
void(* plugin_interface_t::nic_recv)(uint8_t *buf, int size, int cur_pos, int start, int stop)
This callback is invoked when a network packet is received by NIC.
Referenced by TEMU_nic_receive().
void(* plugin_interface_t::nic_send)(uint32_t addr, int size, uint8_t *buf)
This callback is invoked when a network packet is sent out by NIC.
Referenced by TEMU_nic_send().
void(* plugin_interface_t::plugin_cleanup)()
callback for cleaning up states in plugin. TEMU plugin must release all allocated resources in this function
Referenced by do_unload_plugin().
void(* plugin_interface_t::pre_mem_write)(uint32_t virt_addr, uint32_t phys_addr, int size)
Referenced by __attribute__().
void(* plugin_interface_t::read_disk_taint)(uint64_t addr, uint8_t *record, void *opaque)
Referenced by taintcheck_chk_hdin(), and taintcheck_chk_hdread().
void(* plugin_interface_t::reg_read)(uint32_t regidx, int size)
This callback is invoked when the current instruction reads a register.
Parameters:
regidx register index, e.g., the index of R_BH is R_EBX*4 + 1
size size of register in bytes
Referenced by __attribute__().
void(* plugin_interface_t::reg_write)(uint32_t regidx, int size)
This callback is invoked when the current instruction writes a register.
Parameters:
regidx register index, e.g., the index of R_BH is R_EBX*4 + 1
size size of register in bytes
void(* plugin_interface_t::send_keystroke)(int reg)
Referenced by TEMU_read_keystroke().
void(* plugin_interface_t::taint_disk)(uint64_t addr, uint8_t *record, void *opaque)
Referenced by taintcheck_chk_hdout(), and taintcheck_chk_hdwrite().
void(* plugin_interface_t::taint_propagate)(int nr_src, taint_operand_t *src_oprnds, taint_operand_t *dst_oprnd, int mode)
This callback customizes its own policy for taint propagation.
TEMU asks plugin how to propagate tainted data. If the plugin does not want to customize the propagation policy, it can simply specify default_taint_propagate().
Parameters:
nr_src number of source operands
src_oprnds array of source operands
dst_oprnd destination operand
mode mode of propagation (either direct move or transformation)
Referenced by __attribute__(), and reg2reg_internal().
int plugin_interface_t::taint_record_size
size of taint record for each tainted byte. TEMU sees taint record as untyped buffer, so it only cares about the size of taint record
Definition at line 307 of file TEMU_main.h.
Referenced by __attribute__(), default_taint_propagate(), fast_clean_memory(), fast_taint_memory(), LIST_HEAD(), reg2reg_internal(), taintcheck_check_eip(), taintcheck_check_virtmem(), taintcheck_chk_hdin(), taintcheck_chk_hdout(), taintcheck_chk_hdread(), taintcheck_chk_hdwrite(), taintcheck_create(), taintcheck_disk_check(), taintcheck_load(), taintcheck_memory_check(), taintcheck_nic_in(), taintcheck_nic_out(), taintcheck_nic_readbuf(), taintcheck_nic_writebuf(), taintcheck_register_check(), taintcheck_save(), taintcheck_taint_memory(), taintcheck_taint_register(), and taintcheck_taint_virtmem().
term_cmd_t* plugin_interface_t::term_cmds
array of terminal commands
Definition at line 295 of file TEMU_main.h.
The documentation for this struct was generated from the following file:
TEMU_main.h