TEMU: taintcheck.c File Reference
TEMU: Dynamic Binary Analysis Platform
taintcheck.c File Reference
Data Structures
struct _tpage_entry
struct disk_record
Typedefs
typedef struct disk_record disk_record_t
typedef struct _tpage_entry tpage_entry_t
Functions
void __attribute__ ((fastcall))
Propagate taint info from register to memory.
static void clean_memory (uint32_t addr, int size)
static void clean_register (int regidx, int size)
static uint8_t clear_zero (uint32_t value, int size, uint8_t taint)
void default_taint_propagate (int nr_src, taint_operand_t *src_oprnds, taint_operand_t *dst_oprnd, int mode)
void do_info_taintmem (void)
static void fast_clean_memory (uint32_t addr, int size)
static uint64_t fast_taint_mem_check (uint32_t addr, int size)
fast version memory taint check, without boundary check
static void fast_taint_memory (uint32_t addr, int size, uint64_t taint)
static LIST_HEAD (disk_record_list_head, disk_record)
static void reg2reg_internal (int sregidx, int dregidx, int size)
static uint64_t size_to_taint (int size)
static uint64_t taint_mem_check (uint32_t addr, int size)
static void taint_memory (uint32_t addr, int size, uint64_t taint)
static uint8_t taint_reg_check (int regidx, int size)
static void taint_register (int regidx, int size, uint64_t taint)
int taintcheck_check_eip (uint32_t reg)
uint64_t taintcheck_check_virtmem (uint32_t vaddr, uint32_t size, void *records)
int taintcheck_chk_hdin (int size, int64_t sect_num, uint32_t offset, void *s)
int taintcheck_chk_hdout (int size, int64_t sect_num, uint32_t offset, void *s)
int taintcheck_chk_hdread (uint32_t paddr, int size, int64_t sect_num, void *s)
int taintcheck_chk_hdwrite (uint32_t paddr, int size, int64_t sect_num, void *s)
void taintcheck_clean_memreg ()
void taintcheck_cleanup ()
void taintcheck_clear_ones (int reg, int size, uint32_t val)
void taintcheck_clear_zeros (int reg, int size, uint32_t val)
void taintcheck_code2TN (uint32_t vaddr, uint32_t regid, int size)
int taintcheck_create ()
uint64_t taintcheck_disk_check (uint64_t index, int offset, int size, uint8_t *record, void *bs)
int taintcheck_get_sizeof_taintmem ()
int taintcheck_init ()
int taintcheck_jnz_T0_label ()
static int taintcheck_load (QEMUFile *f, void *opaque, int version_id)
uint64_t taintcheck_memory_check (uint32_t addr, int size, uint8_t *records)
void taintcheck_mov_i2m ()
void taintcheck_mov_m2r (int base, int index, int dreg_id)
void taintcheck_mov_r2m (int base, int index, int reg_id)
int taintcheck_nic_in (uint32_t addr, int size)
int taintcheck_nic_out (uint32_t addr, int size)
uint64_t taintcheck_nic_readbuf (uint32_t addr, int size, uint8_t *records)
int taintcheck_nic_writebuf (uint32_t addr, int size, uint64_t bitmap, uint8_t *records)
int taintcheck_patch ()
void taintcheck_reg2TN (int reg, int t, int size)
void taintcheck_regh2TN (int reg, int t)
uint64_t taintcheck_register_check (int reg, int offset, int size, uint8_t *records)
static void taintcheck_save (QEMUFile *f, void *opaque)
uint32_t taintcheck_sidt ()
int taintcheck_taint_memory (uint32_t addr, int size, uint64_t taint, uint8_t *records)
int taintcheck_taint_register (int reg, int offset, int size, uint64_t taint, uint8_t *records)
void taintcheck_taint_virtmem (uint32_t vaddr, uint32_t size, uint64_t taint, void *records)
Variables
uint32_t eflags_bitmap = 0
bitmap for eflags
uint8_t * eflags_records = NULL
taint records for eflags
int impact_propagate = 1
int insn_tainted = 0
flag that indicates if the current instruction propagates taint
uint64_t nic_bitmap [1024 *32/64]
bitmap for nic
uint8_t * nic_records = NULL
taint records for nic
uint64_t regs_bitmap = 0
bitmap for registers
uint8_t * regs_records = NULL
taint records for registers
int taintcheck_keyorigin = 0
static tpage_entry_t ** tpage_table = NULL
memory page table
Typedef Documentation
typedef struct disk_record disk_record_t
typedef struct _tpage_entry tpage_entry_t
An internal data structure for holding 64-byte taint information in memory
Function Documentation
void __attribute__ ((fastcall))
Propagate taint info from register to memory.
Definition at line 198 of file taintcheck.c.
References taint_operand_t::addr, clear_zero(), fast_clean_memory(), fast_taint_memory(), insn_tainted, plugin_interface_t::mem_write, plugin_interface_t::pre_mem_write, _tpage_entry::records, taint_operand_t::records, plugin_interface_t::reg_read, regs_records, taint_operand_t::size, taint_operand_t::taint, plugin_interface_t::taint_propagate, plugin_interface_t::taint_record_size, taint_reg_check(), TEMU_emulation_started, temu_plugin, and taint_operand_t::type.
static void clean_memory (uint32_t addr, int size) [static]
Definition at line 150 of file taintcheck.c.
References fast_clean_memory().
Referenced by taintcheck_taint_memory().
static void clean_register (int regidx, int size) [inline, static]
Definition at line 173 of file taintcheck.c.
References regs_bitmap.
Referenced by reg2reg_internal(), taintcheck_jnz_T0_label(), taintcheck_reg2TN(), and taintcheck_regh2TN().
static uint8_t clear_zero (uint32_t value, int size, uint8_t taint) [inline, static]
Definition at line 179 of file taintcheck.c.
Referenced by __attribute__(), reg2reg_internal(), and taintcheck_clear_zeros().
void do_info_taintmem (void)
Definition at line 1793 of file taintcheck.c.
References taintcheck_get_sizeof_taintmem(), and term_printf().
static void fast_clean_memory (uint32_t addr, int size) [static]
Definition at line 130 of file taintcheck.c.
References _tpage_entry::bitmap, _tpage_entry::records, size_to_taint(), plugin_interface_t::taint_record_size, and temu_plugin.
Referenced by __attribute__(), and clean_memory().
static uint64_t fast_taint_mem_check (uint32_t addr, int size) [inline, static]
fast version memory taint check, without boundary check
Definition at line 74 of file taintcheck.c.
References _tpage_entry::bitmap, and size_to_taint().
Referenced by taint_mem_check().
static void fast_taint_memory (uint32_t addr, int size, uint64_t taint) [static]
Definition at line 91 of file taintcheck.c.
References _tpage_entry::bitmap, size_to_taint(), plugin_interface_t::taint_record_size, and temu_plugin.
Referenced by __attribute__(), and taint_memory().
static LIST_HEAD (disk_record_list_head , disk_record) [static]
Definition at line 943 of file taintcheck.c.
References size_to_taint(), plugin_interface_t::taint_record_size, taintcheck_taint_disk(), TEMU_emulation_started, and temu_plugin.
static void reg2reg_internal (int sregidx, int dregidx, int size) [inline, static]
Definition at line 475 of file taintcheck.c.
References taint_operand_t::addr, clean_register(), clear_zero(), insn_tainted, taint_operand_t::records, regs_bitmap, regs_records, taint_operand_t::size, taint_operand_t::taint, plugin_interface_t::taint_propagate, plugin_interface_t::taint_record_size, taint_reg_check(), taint_register(), temu_plugin, and taint_operand_t::type.
static uint64_t size_to_taint (int size) [inline, static]
Definition at line 62 of file taintcheck.c.
Referenced by fast_clean_memory(), fast_taint_mem_check(), fast_taint_memory(), LIST_HEAD(), taint_memory(), taintcheck_disk_check(), taintcheck_nic_readbuf(), taintcheck_nic_writebuf(), and taintcheck_taint_virtmem().
static uint64_t taint_mem_check (uint32_t addr, int size) [inline, static]
Definition at line 80 of file taintcheck.c.
References fast_taint_mem_check().
Referenced by taintcheck_memory_check(), and taintcheck_patch().
static void taint_memory (uint32_t addr, int size, uint64_t taint) [static]
Definition at line 118 of file taintcheck.c.
References fast_taint_memory(), and size_to_taint().
Referenced by taintcheck_chk_hdread(), and taintcheck_taint_memory().
static uint8_t taint_reg_check (int regidx, int size) [inline, static]
Definition at line 68 of file taintcheck.c.
References regs_bitmap.
Referenced by __attribute__(), reg2reg_internal(), taintcheck_check_eip(), taintcheck_chk_hdout(), taintcheck_clear_ones(), taintcheck_clear_zeros(), taintcheck_jnz_T0_label(), taintcheck_nic_out(), and taintcheck_register_check().
static void taint_register (int regidx, int size, uint64_t taint) [inline, static]
Definition at line 163 of file taintcheck.c.
References regs_bitmap.
Referenced by reg2reg_internal(), taintcheck_chk_hdin(), taintcheck_clear_ones(), taintcheck_clear_zeros(), and taintcheck_taint_register().
int taintcheck_check_eip (uint32_t reg)
Definition at line 1477 of file taintcheck.c.
References plugin_interface_t::eip_tainted, plugin_interface_t::memreg_eip_change, regs_records, should_monitor, plugin_interface_t::taint_record_size, taint_reg_check(), TEMU_emulation_started, and temu_plugin.
int taintcheck_chk_hdin (int size, int64_t sect_num, uint32_t offset, void * s)
Definition at line 1076 of file taintcheck.c.
References plugin_interface_t::read_disk_taint, regs_records, plugin_interface_t::taint_record_size, taint_register(), taintcheck_disk_check(), TEMU_emulation_started, and temu_plugin.
int taintcheck_chk_hdout (int size, int64_t sect_num, uint32_t offset, void * s)
Definition at line 1048 of file taintcheck.c.
References regs_records, plugin_interface_t::taint_disk, plugin_interface_t::taint_record_size, taint_reg_check(), taintcheck_taint_disk(), TEMU_emulation_started, and temu_plugin.
int taintcheck_chk_hdread (uint32_t paddr, int size, int64_t sect_num, void * s)
Definition at line 1144 of file taintcheck.c.
References plugin_interface_t::read_disk_taint, taint_memory(), plugin_interface_t::taint_record_size, taintcheck_disk_check(), TEMU_emulation_started, and temu_plugin.
int taintcheck_chk_hdwrite (uint32_t paddr, int size, int64_t sect_num, void * s)
Definition at line 1115 of file taintcheck.c.
References _tpage_entry::bitmap, _tpage_entry::records, plugin_interface_t::taint_disk, plugin_interface_t::taint_record_size, taintcheck_taint_disk(), TEMU_emulation_started, and temu_plugin.
void taintcheck_clean_memreg ()
Definition at line 1200 of file taintcheck.c.
References regs_bitmap.
Referenced by taintcheck_load().
void taintcheck_cleanup ()
Definition at line 1631 of file taintcheck.c.
References deregister_savevm(), eflags_records, nic_bitmap, nic_records, regs_bitmap, and regs_records.
Referenced by do_unload_plugin().
void taintcheck_clear_ones (int reg, int size, uint32_t val)
Definition at line 852 of file taintcheck.c.
References taint_reg_check(), taint_register(), and TEMU_emulation_started.
void taintcheck_clear_zeros (int reg, int size, uint32_t val)
Definition at line 870 of file taintcheck.c.
References clear_zero(), taint_reg_check(), taint_register(), and TEMU_emulation_started.
void taintcheck_code2TN (uint32_t vaddr, uint32_t regid, int size)
Definition at line 1742 of file taintcheck.c.
References TEMU_get_phys_addr().
int taintcheck_create ()
Definition at line 1593 of file taintcheck.c.
References eflags_records, nic_bitmap, nic_records, register_savevm(), regs_bitmap, regs_records, plugin_interface_t::taint_record_size, taintcheck_load(), taintcheck_save(), and temu_plugin.
Referenced by do_load_plugin().
uint64_t taintcheck_disk_check (uint64_t index, int offset, int size, uint8_t * record, void * bs)
Definition at line 1010 of file taintcheck.c.
References size_to_taint(), plugin_interface_t::taint_record_size, TEMU_emulation_started, and temu_plugin.
Referenced by taintcheck_chk_hdin(), and taintcheck_chk_hdread().
int taintcheck_init ()
Definition at line 1583 of file taintcheck.c.
Referenced by TEMU_init().
int taintcheck_jnz_T0_label ()
Definition at line 1461 of file taintcheck.c.
References plugin_interface_t::cjmp, clean_register(), insn_tainted, should_monitor, taint_reg_check(), TEMU_emulation_started, and temu_plugin.
static int taintcheck_load (QEMUFile * f, void * opaque, int version_id) [static]
Definition at line 1541 of file taintcheck.c.
References _tpage_entry::bitmap, _tpage_entry::records, regs_bitmap, regs_records, plugin_interface_t::taint_record_size, taintcheck_clean_memreg(), and temu_plugin.
Referenced by taintcheck_create().
void taintcheck_mov_i2m ()
Definition at line 1676 of file taintcheck.c.
References taintcheck_mem_clean().
void taintcheck_mov_m2r (int base, int index, int dreg_id)
Definition at line 1686 of file taintcheck.c.
References taintcheck_fn2regs(), and taintcheck_mem2reg().
void taintcheck_mov_r2m (int base, int index, int reg_id)
Definition at line 1699 of file taintcheck.c.
References taintcheck_fn2regs(), and taintcheck_reg2mem().
int taintcheck_nic_in (uint32_t addr, int size)
Definition at line 1275 of file taintcheck.c.
References plugin_interface_t::taint_record_size, taintcheck_nic_readbuf(), taintcheck_taint_register(), and temu_plugin.
Referenced by TEMU_nic_in().
int taintcheck_nic_out (uint32_t addr, int size)
Definition at line 1263 of file taintcheck.c.
References regs_records, plugin_interface_t::taint_record_size, taint_reg_check(), taintcheck_nic_writebuf(), and temu_plugin.
Referenced by TEMU_nic_out().
uint64_t taintcheck_nic_readbuf (uint32_t addr, int size, uint8_t * records)
Definition at line 1238 of file taintcheck.c.
References disk_record::index, nic_bitmap, nic_records, size_to_taint(), plugin_interface_t::taint_record_size, TEMU_emulation_started, and temu_plugin.
Referenced by taintcheck_nic_in().
int taintcheck_nic_writebuf (uint32_t addr, int size, uint64_t bitmap, uint8_t * records)
Definition at line 1213 of file taintcheck.c.
References disk_record::index, nic_bitmap, nic_records, size_to_taint(), plugin_interface_t::taint_record_size, TEMU_emulation_started, and temu_plugin.
Referenced by taintcheck_nic_out().
int taintcheck_patch ()
Definition at line 1287 of file taintcheck.c.
References taint_mem_check(), taintcheck_reg2mem(), TEMU_emulation_started, TEMU_get_phys_addr(), and TEMU_read_mem().
void taintcheck_reg2TN (int reg, int t, int size)
Definition at line 1713 of file taintcheck.c.
References clean_register(), and taintcheck_reg2reg().
void taintcheck_regh2TN (int reg, int t)
Definition at line 1719 of file taintcheck.c.
References clean_register(), and taintcheck_reg2reg_shift().
static void taintcheck_save (QEMUFile * f, void * opaque) [static]
Definition at line 1508 of file taintcheck.c.
References disk_record::bitmap, regs_bitmap, regs_records, plugin_interface_t::taint_record_size, and temu_plugin.
Referenced by taintcheck_create().
uint32_t taintcheck_sidt (void)
Definition at line 1725 of file taintcheck.c.
References plugin_interface_t::cheat_sidt, TEMU_emulation_started, and temu_plugin.
Variable Documentation
uint32_t eflags_bitmap = 0
bitmap for eflags
Definition at line 55 of file taintcheck.c.
uint8_t* eflags_records = NULL
taint records for eflags
Definition at line 56 of file taintcheck.c.
Referenced by taintcheck_cleanup(), and taintcheck_create().
int impact_propagate = 1
Definition at line 34 of file taintcheck.c.
int insn_tainted = 0
flag that indicates if the current instruction propagates taint
Definition at line 60 of file taintcheck.c.
Referenced by __attribute__(), reg2reg_internal(), taintcheck_jnz_T0_label(), TEMU_insn_begin(), and TEMU_insn_end().
uint64_t nic_bitmap[1024 *32/64]
bitmap for nic
Definition at line 51 of file taintcheck.c.
Referenced by taintcheck_cleanup(), taintcheck_create(), taintcheck_nic_readbuf(), and taintcheck_nic_writebuf().
uint8_t* nic_records = NULL
taint records for nic
Definition at line 52 of file taintcheck.c.
Referenced by taintcheck_cleanup(), taintcheck_create(), taintcheck_nic_readbuf(), and taintcheck_nic_writebuf().
uint64_t regs_bitmap = 0
bitmap for registers
Definition at line 47 of file taintcheck.c.
Referenced by clean_register(), reg2reg_internal(), taint_reg_check(), taint_register(), taintcheck_clean_memreg(), taintcheck_cleanup(), taintcheck_create(), taintcheck_load(), and taintcheck_save().
uint8_t* regs_records = NULL
taint records for registers
Definition at line 48 of file taintcheck.c.
Referenced by __attribute__(), reg2reg_internal(), taintcheck_check_eip(), taintcheck_chk_hdin(), taintcheck_chk_hdout(), taintcheck_cleanup(), taintcheck_create(), taintcheck_load(), taintcheck_nic_out(), taintcheck_register_check(), taintcheck_save(), and taintcheck_taint_register().
int taintcheck_keyorigin = 0
Definition at line 59 of file taintcheck.c.
tpage_entry_t** tpage_table = NULL [static]
memory page table
Definition at line 49 of file taintcheck.c.