TEMU: taintcheck.h File Reference
TEMU: Dynamic Binary Analysis Platform
taintcheck.h File Reference
Data Structures
struct taint_operand_t
Functions
void __attribute__ ((fastcall)) taintcheck_logic_T0_T1()
Propagate taint info from register to memory.
void default_taint_propagate (int nr_src, taint_operand_t *src_oprnds, taint_operand_t *dst_oprnd, int mode)
void do_info_taintmem (void)
void taintcheck_bswap (int reg, int size) __attribute__((fastcall))
int taintcheck_check_eip (uint32_t reg)
uint64_t taintcheck_check_virtmem (uint32_t vaddr, uint32_t size, void *records)
int taintcheck_chk_hdin (int size, int64_t sect_num, uint32_t offset, void *s)
int taintcheck_chk_hdout (int size, int64_t sect_num, uint32_t offset, void *s)
int taintcheck_chk_hdread (uint32_t paddr, int size, int64_t sect_num, void *s)
int taintcheck_chk_hdwrite (uint32_t paddr, int size, int64_t sect_num, void *s)
void taintcheck_clean_memory (uint32_t phys_addr, int size) __attribute__((fastcall))
void taintcheck_clean_memreg ()
void taintcheck_cleanup ()
void taintcheck_clear_ones (int reg, int size, uint32_t val)
void taintcheck_clear_zeros (int reg, int size, uint32_t val)
void taintcheck_code2TN (uint32_t vaddr, uint32_t regid, int size)
int taintcheck_create ()
void taintcheck_flag2reg (uint32_t mask, int regidx, int size) __attribute__((fastcall))
void taintcheck_fn1reg (int reg, int size) __attribute__((fastcall))
void taintcheck_fn2regs (int sreg1, int sreg2, int dreg, int size) __attribute__((fastcall))
int taintcheck_get_sizeof_taintmem ()
int taintcheck_init ()
int taintcheck_jnz_T0_label ()
void taintcheck_mem2reg (void *ptr, int size, int reg) __attribute__((fastcall))
void taintcheck_mem_clean (void *ptr, int size) __attribute__((fastcall))
uint64_t taintcheck_memory_check (uint32_t addr, int size, uint8_t *records)
void taintcheck_mov_i2m ()
void taintcheck_mov_m2r (int base, int index, int dreg_id)
void taintcheck_mov_r2m (int base, int index, int reg_id)
int taintcheck_nic_in (uint32_t addr, int size)
int taintcheck_nic_out (uint32_t addr, int size)
uint64_t taintcheck_nic_readbuf (uint32_t addr, int size, uint8_t *records)
int taintcheck_nic_writebuf (uint32_t addr, int size, uint64_t bitmap, uint8_t *records)
int taintcheck_patch ()
void taintcheck_reg2flag (int regidx, int size, uint32_t mask) __attribute__((fastcall))
void taintcheck_reg2mem (int reg, int size, void *ptr) __attribute__((fastcall))
void taintcheck_reg2reg (int sreg, int dreg, int size) __attribute__((fastcall))
void taintcheck_reg2reg_shift (int sregidx, int dregidx, int size) __attribute__((fastcall))
void taintcheck_reg2TN (int reg, int t, int size)
void taintcheck_reg_clean (int reg) __attribute__((fastcall))
void taintcheck_reg_clean2 (int regidx, int size) __attribute__((fastcall))
void taintcheck_regh2TN (int reg, int t)
uint64_t taintcheck_register_check (int reg, int offset, int size, uint8_t *records)
uint32_t taintcheck_sidt (void)
int taintcheck_taint_disk (uint64_t index, uint64_t taint, int offset, int size, uint8_t *record, void *bs)
int taintcheck_taint_memory (uint32_t addr, int size, uint64_t taint, uint8_t *records)
int taintcheck_taint_register (int reg, int offset, int size, uint64_t taint, uint8_t *records)
void taintcheck_taint_virtmem (uint32_t vaddr, uint32_t size, uint64_t taint, void *records)
static void taintcheck_update_all_eflags ()
void taintcheck_update_cr3 ()
void taintcheck_update_eflags (uint32_t mask) __attribute__((fastcall))
Variables
void int int int dreg
int impact_propagate
int insn_tainted
flag that indicates if the current instruction propagates taint
uint64_t nic_bitmap [1024 *32/64]
bitmap for nic
uint8_t * nic_records
taint records for nic
uint64_t regs_bitmap
bitmap for registers
uint8_t * regs_records
taint records for registers
void int int int int size
void int sreg2
void int int sreg3
Detailed Description
Author:
: Heng Yin <hyin@ece.cmu.edu>
Definition in file taintcheck.h.
Function Documentation
void __attribute__ ((fastcall))
Propagate taint info from register to memory.
Definition at line 198 of file taintcheck.c.
References taint_operand_t::addr, clear_zero(), fast_clean_memory(), fast_taint_memory(), insn_tainted, plugin_interface_t::mem_write, plugin_interface_t::pre_mem_write, _tpage_entry::records, taint_operand_t::records, plugin_interface_t::reg_read, regs_records, taint_operand_t::size, taint_operand_t::taint, plugin_interface_t::taint_propagate, plugin_interface_t::taint_record_size, taint_reg_check(), TEMU_emulation_started, temu_plugin, and taint_operand_t::type.
void do_info_taintmem (void)
Definition at line 1793 of file taintcheck.c.
References taintcheck_get_sizeof_taintmem(), and term_printf().
void taintcheck_bswap (int reg, int size)
int taintcheck_check_eip (uint32_t reg)
Definition at line 1477 of file taintcheck.c.
References plugin_interface_t::eip_tainted, plugin_interface_t::memreg_eip_change, regs_records, should_monitor, plugin_interface_t::taint_record_size, taint_reg_check(), TEMU_emulation_started, and temu_plugin.
int taintcheck_chk_hdin (int size, int64_t sect_num, uint32_t offset, void * s)
Definition at line 1076 of file taintcheck.c.
References plugin_interface_t::read_disk_taint, regs_records, plugin_interface_t::taint_record_size, taint_register(), taintcheck_disk_check(), TEMU_emulation_started, and temu_plugin.
int taintcheck_chk_hdout (int size, int64_t sect_num, uint32_t offset, void * s)
Definition at line 1048 of file taintcheck.c.
References regs_records, plugin_interface_t::taint_disk, plugin_interface_t::taint_record_size, taint_reg_check(), taintcheck_taint_disk(), TEMU_emulation_started, and temu_plugin.
int taintcheck_chk_hdread (uint32_t paddr, int size, int64_t sect_num, void * s)
Definition at line 1144 of file taintcheck.c.
References plugin_interface_t::read_disk_taint, taint_memory(), plugin_interface_t::taint_record_size, taintcheck_disk_check(), TEMU_emulation_started, and temu_plugin.
int taintcheck_chk_hdwrite (uint32_t paddr, int size, int64_t sect_num, void * s)
Definition at line 1115 of file taintcheck.c.
References _tpage_entry::bitmap, _tpage_entry::records, plugin_interface_t::taint_disk, plugin_interface_t::taint_record_size, taintcheck_taint_disk(), TEMU_emulation_started, and temu_plugin.
void taintcheck_clean_memory (uint32_t phys_addr, int size)
void taintcheck_clean_memreg ()
Definition at line 1200 of file taintcheck.c.
References regs_bitmap.
Referenced by taintcheck_load().
void taintcheck_cleanup ()
Definition at line 1631 of file taintcheck.c.
References deregister_savevm(), eflags_records, nic_bitmap, nic_records, regs_bitmap, and regs_records.
Referenced by do_unload_plugin().
void taintcheck_clear_ones (int reg, int size, uint32_t val)
Definition at line 852 of file taintcheck.c.
References taint_reg_check(), taint_register(), and TEMU_emulation_started.
void taintcheck_clear_zeros (int reg, int size, uint32_t val)
Definition at line 870 of file taintcheck.c.
References clear_zero(), taint_reg_check(), taint_register(), and TEMU_emulation_started.
void taintcheck_code2TN (uint32_t vaddr, uint32_t regid, int size)
Definition at line 1742 of file taintcheck.c.
References TEMU_get_phys_addr().
int taintcheck_create ()
Definition at line 1593 of file taintcheck.c.
References eflags_records, nic_bitmap, nic_records, register_savevm(), regs_bitmap, regs_records, plugin_interface_t::taint_record_size, taintcheck_load(), taintcheck_save(), and temu_plugin.
Referenced by do_load_plugin().
void taintcheck_flag2reg (uint32_t mask, int regidx, int size)
void taintcheck_fn1reg (int reg, int size)
void taintcheck_fn2regs (int sreg1, int sreg2, int dreg, int size)
Referenced by taintcheck_mov_m2r(), and taintcheck_mov_r2m().
int taintcheck_init ()
Definition at line 1583 of file taintcheck.c.
Referenced by TEMU_init().
int taintcheck_jnz_T0_label ()
Definition at line 1461 of file taintcheck.c.
References plugin_interface_t::cjmp, clean_register(), insn_tainted, should_monitor, taint_reg_check(), TEMU_emulation_started, and temu_plugin.
void taintcheck_mem2reg (void * ptr, int size, int reg)
Referenced by taintcheck_mov_m2r().
void taintcheck_mem_clean (void * ptr, int size)
Referenced by taintcheck_mov_i2m().
void taintcheck_mov_i2m ()
Definition at line 1676 of file taintcheck.c.
References taintcheck_mem_clean().
void taintcheck_mov_m2r (int base, int index, int dreg_id)
Definition at line 1686 of file taintcheck.c.
References taintcheck_fn2regs(), and taintcheck_mem2reg().
void taintcheck_mov_r2m (int base, int index, int reg_id)
Definition at line 1699 of file taintcheck.c.
References taintcheck_fn2regs(), and taintcheck_reg2mem().
int taintcheck_nic_in (uint32_t addr, int size)
Definition at line 1275 of file taintcheck.c.
References plugin_interface_t::taint_record_size, taintcheck_nic_readbuf(), taintcheck_taint_register(), and temu_plugin.
Referenced by TEMU_nic_in().
int taintcheck_nic_out (uint32_t addr, int size)
Definition at line 1263 of file taintcheck.c.
References regs_records, plugin_interface_t::taint_record_size, taint_reg_check(), taintcheck_nic_writebuf(), and temu_plugin.
Referenced by TEMU_nic_out().
uint64_t taintcheck_nic_readbuf (uint32_t addr, int size, uint8_t * records)
Definition at line 1238 of file taintcheck.c.
References disk_record::index, nic_bitmap, nic_records, size_to_taint(), plugin_interface_t::taint_record_size, TEMU_emulation_started, and temu_plugin.
Referenced by taintcheck_nic_in().
int taintcheck_nic_writebuf (uint32_t addr, int size, uint64_t bitmap, uint8_t * records)
Definition at line 1213 of file taintcheck.c.
References disk_record::index, nic_bitmap, nic_records, size_to_taint(), plugin_interface_t::taint_record_size, TEMU_emulation_started, and temu_plugin.
Referenced by taintcheck_nic_out().
int taintcheck_patch ()
Definition at line 1287 of file taintcheck.c.
References taint_mem_check(), taintcheck_reg2mem(), TEMU_emulation_started, TEMU_get_phys_addr(), and TEMU_read_mem().
void taintcheck_reg2flag (int regidx, int size, uint32_t mask)
void taintcheck_reg2mem (int reg, int size, void * ptr)
Referenced by taintcheck_mov_r2m(), and taintcheck_patch().
void taintcheck_reg2reg (int sreg, int dreg, int size)
Referenced by taintcheck_reg2TN().
void taintcheck_reg2reg_shift (int sregidx, int dregidx, int size)
Referenced by taintcheck_regh2TN().
void taintcheck_reg2TN (int reg, int t, int size)
Definition at line 1713 of file taintcheck.c.
References clean_register(), and taintcheck_reg2reg().
void taintcheck_reg_clean (int reg)
Referenced by alloca_probe_ret(), and InterlockedPushEntrySList_call().
void taintcheck_reg_clean2 (int regidx, int size)
void taintcheck_regh2TN (int reg, int t)
Definition at line 1719 of file taintcheck.c.
References clean_register(), and taintcheck_reg2reg_shift().
uint32_t taintcheck_sidt (void)
Definition at line 1725 of file taintcheck.c.
References plugin_interface_t::cheat_sidt, TEMU_emulation_started, and temu_plugin.
int taintcheck_taint_disk (uint64_t index, uint64_t taint, int offset, int size, uint8_t * record, void * bs)
Referenced by LIST_HEAD(), taintcheck_chk_hdout(), and taintcheck_chk_hdwrite().
static void taintcheck_update_all_eflags () [inline, static]
Definition at line 209 of file taintcheck.h.
References taintcheck_update_eflags().
void taintcheck_update_cr3 ()
void taintcheck_update_eflags (uint32_t mask)
Referenced by taintcheck_update_all_eflags().
Variable Documentation
void int int int dreg
Definition at line 156 of file taintcheck.h.
int impact_propagate
Definition at line 34 of file taintcheck.c.
int insn_tainted
flag that indicates if the current instruction propagates taint
Definition at line 60 of file taintcheck.c.
Referenced by __attribute__(), reg2reg_internal(), taintcheck_jnz_T0_label(), TEMU_insn_begin(), and TEMU_insn_end().
uint64_t nic_bitmap[1024 *32/64]
bitmap for nic
Definition at line 51 of file taintcheck.c.
Referenced by taintcheck_cleanup(), taintcheck_create(), taintcheck_nic_readbuf(), and taintcheck_nic_writebuf().
uint8_t* nic_records
taint records for nic
Definition at line 52 of file taintcheck.c.
Referenced by taintcheck_cleanup(), taintcheck_create(), taintcheck_nic_readbuf(), and taintcheck_nic_writebuf().
uint64_t regs_bitmap
bitmap for registers
Definition at line 47 of file taintcheck.c.
Referenced by clean_register(), reg2reg_internal(), taint_reg_check(), taint_register(), taintcheck_clean_memreg(), taintcheck_cleanup(), taintcheck_create(), taintcheck_load(), and taintcheck_save().
uint8_t* regs_records
taint records for registers
Definition at line 48 of file taintcheck.c.
Referenced by __attribute__(), reg2reg_internal(), taintcheck_check_eip(), taintcheck_chk_hdin(), taintcheck_chk_hdout(), taintcheck_cleanup(), taintcheck_create(), taintcheck_load(), taintcheck_nic_out(), taintcheck_register_check(), taintcheck_save(), and taintcheck_taint_register().
void int int int int size
Definition at line 156 of file taintcheck.h.
Referenced by parse_module(), procmod_load(), TEMU_register_rw(), TEMU_save(), and update_proc().
void int sreg2
Definition at line 156 of file taintcheck.h.
void int int sreg3
Definition at line 156 of file taintcheck.h.