TEMU: TEMU_lib.h File Reference
TEMU: Dynamic Binary Analysis Platform
TEMU_lib.h File Reference
Typedefs
typedef int LoadStateHandler (QEMUFile *f, void *opaque, int version_id)
typedef struct QEMUClock QEMUClock
typedef struct QEMUFile QEMUFile
typedef struct QEMUTimer QEMUTimer
typedef void QEMUTimerCB (void *opaque)
typedef void SaveStateHandler (QEMUFile *f, void *opaque)
Functions
int deregister_savevm (const char *idstr, int instance_id)
Deregister a VM entity.
void do_loadvm (const char *name)
Load a previously saved VM snapshot.
void do_savevm (const char *name)
Save the current VM states into a snapshot.
void do_send_key (const char *string)
Send a keystroke.
void qemu_del_timer (QEMUTimer *ts)
void qemu_fclose (QEMUFile *f)
void qemu_fflush (QEMUFile *f)
QEMUFile * qemu_fopen (const char *filename, const char *mode)
void qemu_free_timer (QEMUTimer *ts)
Free a timer.
unsigned int qemu_get_be16 (QEMUFile *f)
unsigned int qemu_get_be32 (QEMUFile *f)
uint64_t qemu_get_be64 (QEMUFile *f)
int qemu_get_buffer (QEMUFile *f, uint8_t *buf, int size)
int qemu_get_byte (QEMUFile *f)
int64_t qemu_get_clock (QEMUClock *clock)
void qemu_mod_timer (QEMUTimer *ts, int64_t expire_time)
Set up a timeout.
QEMUTimer * qemu_new_timer (QEMUClock *clock, QEMUTimerCB *cb, void *opaque)
Create a timer.
void qemu_put_be16 (QEMUFile *f, unsigned int v)
void qemu_put_be32 (QEMUFile *f, unsigned int v)
void qemu_put_be64 (QEMUFile *f, uint64_t v)
void qemu_put_buffer (QEMUFile *f, const uint8_t *buf, int size)
void qemu_put_byte (QEMUFile *f, int v)
int qemu_timer_pending (QEMUTimer *ts)
Check if the timer is pending.
int register_savevm (const char *idstr, int instance_id, int version_id, SaveStateHandler *save_state, LoadStateHandler *load_state, void *opaque)
Register a VM entity for saving and restoring VM states.
void vm_stop (int reason)
Pause VM.
Variables
int64_t ticks_per_sec
QEMUClock * vm_clock
Detailed Description
Author:
: Heng Yin <hyin@ece.cmu.edu>
Definition in file TEMU_lib.h.
Typedef Documentation
typedef int LoadStateHandler(QEMUFile *f, void *opaque, int version_id)
Definition at line 50 of file TEMU_lib.h.
typedef struct QEMUClock QEMUClock
Definition at line 22 of file TEMU_lib.h.
typedef struct QEMUFile QEMUFile
Definition at line 35 of file TEMU_lib.h.
typedef struct QEMUTimer QEMUTimer
Definition at line 23 of file TEMU_lib.h.
typedef void QEMUTimerCB(void *opaque)
Definition at line 24 of file TEMU_lib.h.
typedef void SaveStateHandler(QEMUFile *f, void *opaque)
Definition at line 49 of file TEMU_lib.h.
Function Documentation
void qemu_fclose (QEMUFile * f)
void qemu_fflush (QEMUFile * f)
QEMUFile* qemu_fopen (const char * filename, const char * mode)
unsigned int qemu_get_be16 (QEMUFile * f)
unsigned int qemu_get_be32 (QEMUFile * f)
Referenced by function_map_load(), hookapi_load(), procmod_load(), and TEMU_load().
uint64_t qemu_get_be64 (QEMUFile * f)
int qemu_get_buffer (QEMUFile * f, uint8_t * buf, int size)
Referenced by hookapi_load(), procmod_load(), and TEMU_load().
int qemu_get_byte (QEMUFile * f)
Referenced by hookapi_load().
int64_t qemu_get_clock (QEMUClock * clock)
void qemu_put_be16 (QEMUFile * f, unsigned int v)
void qemu_put_be32 (QEMUFile * f, unsigned int v)
Referenced by function_map_save(), hookapi_save(), procmod_save(), and TEMU_save().
void qemu_put_be64 (QEMUFile * f, uint64_t v)
void qemu_put_buffer (QEMUFile * f, const uint8_t * buf, int size)
Referenced by hookapi_save(), procmod_save(), and TEMU_save().
void qemu_put_byte (QEMUFile * f, int v)
Referenced by hookapi_save().
Variable Documentation
int64_t ticks_per_sec
QEMUClock* vm_clock