TEMU: TEMU_main.c File Reference
TEMU: Dynamic Binary Analysis Platform
TEMU_main.c File Reference
Functions
void do_disable_emulation ()
void do_enable_emulation ()
void do_load_plugin (const char *plugin_path)
void do_unload_plugin ()
void TEMU_after_iret_protected ()
void TEMU_after_loadvm (const char *param)
int TEMU_bdrv_pread (void *bs, int64_t offset, void *buf, int count)
int TEMU_block_begin ()
void TEMU_block_end ()
void TEMU_call_analysis (uint32_t next_eip)
void TEMU_do_interrupt (int intno, int is_int, target_ulong next_eip)
int TEMU_get_page_access (uint32_t addr)
Given a virtual address, this function returns the page access status.
target_ulong TEMU_get_phys_addr (target_ulong addr)
Convert virtual address into physical address.
uint32_t TEMU_get_physaddr_with_cr3 (target_ulong cr3, target_ulong addr)
void TEMU_init ()
void TEMU_insn_begin (uint32_t pc_start)
void TEMU_insn_end ()
static int TEMU_load (QEMUFile *f, void *opaque, int version_id)
void TEMU_loadvm (void *opaque)
int TEMU_memory_rw (uint32_t addr, void *buf, int len, int is_write)
int TEMU_memory_rw_with_cr3 (target_ulong cr3, uint32_t addr, void *buf, int len, int is_write)
void TEMU_nic_in (uint32_t addr, int size)
void TEMU_nic_out (uint32_t addr, int size)
void TEMU_nic_receive (const uint8_t *buf, int size, int cur_pos, int start, int stop)
void TEMU_nic_send (uint32_t addr, int size, uint8_t *buf)
void TEMU_read_keystroke (void *s)
int TEMU_read_mem (uint32_t vaddr, int len, void *buf)
Read from a memory region by its virtual address.
int TEMU_read_mem_with_cr3 (target_ulong cr3, uint32_t vaddr, int len, void *buf)
void TEMU_read_register (int reg_id, void *buf)
Read from a register.
static void TEMU_register_rw (int reg_id, void *buf, int is_write)
static void TEMU_save (QEMUFile *f, void *opaque)
void TEMU_stop_vm ()
Pause the guest system.
void TEMU_update_cpustate ()
void TEMU_update_cr3 ()
void TEMU_virtdev_init ()
static void TEMU_virtdev_write_data (void *opaque, uint32_t addr, uint32_t val)
int TEMU_write_mem (uint32_t vaddr, int len, void *buf)
Write into a memory region by its virtual address.
int TEMU_write_mem_with_cr3 (target_ulong cr3, uint32_t vaddr, int len, void *buf)
void TEMU_write_register (int reg_id, void *buf)
Write into a register.
Variables
CPUState * first_cpu
static FILE * guestlog = NULL
static void * plugin_handle = NULL
int should_monitor = 1
this flag indicates whether the plugin should receive callback
uint32_t * TEMU_cc_op = NULL
target_ulong * TEMU_cpu_cr = NULL
array of CPU control registers, such as CR0 and CR1
int32_t * TEMU_cpu_df = NULL
pointer to DF register
target_ulong * TEMU_cpu_eflags = NULL
pointer to EFLAGS
target_ulong * TEMU_cpu_eip = NULL
pointer to instruction pointer EIP
FPReg * TEMU_cpu_fp_regs = NULL
FPU - array of Floating Point registers.
unsigned int * TEMU_cpu_fp_stt = NULL
FPU - top of Floating Point register stack.
uint8_t * TEMU_cpu_fptags = NULL
FPU - Tag Register.
unsigned int * TEMU_cpu_fpuc = NULL
FPU - Control Register.
unsigned int * TEMU_cpu_fpus = NULL
FPU - Status Register.
SegmentCache * TEMU_cpu_gdt = NULL
pointer to GDT
uint32_t * TEMU_cpu_hflags = NULL
pointer to hidden flags
SegmentCache * TEMU_cpu_idt = NULL
pointer to IDT
SegmentCache * TEMU_cpu_ldt = NULL
pointer to LDT
MMXReg * TEMU_cpu_mmx_regs = NULL
array of MMX registers
target_ulong * TEMU_cpu_regs = NULL
array of CPU general-purpose registers, such as R_EAX, R_EBX
SegmentCache * TEMU_cpu_segs = NULL
array of CPU segment registers, such as R_FS, R_CS
XMMReg * TEMU_cpu_xmm_regs = NULL
array of XMM registers
uint32_t TEMU_eflags = 0
int TEMU_emulation_started = 0
This flag tells if emulation mode is enabled.
void * TEMU_KbdState = NULL
plugin_interface_t * temu_plugin = NULL
static char temu_plugin_path [PATH_MAX] = ""
static FILE * temulog = NULL
Function Documentation
void do_disable_emulation (void)
Definition at line 75 of file TEMU_main.c.
References TEMU_emulation_started, and term_printf().
Referenced by do_unload_plugin(), and TEMU_load().
void do_enable_emulation (void)
Definition at line 60 of file TEMU_main.c.
References TEMU_emulation_started, and term_printf().
Referenced by TEMU_load().
void do_load_plugin (const char * plugin_path)
Definition at line 84 of file TEMU_main.c.
References plugin_interface_t::bdrv_open, plugin_handle, taintcheck_create(), temu_plugin_path, temulog, and term_printf().
Referenced by TEMU_load(), and TEMU_loadvm().
void do_unload_plugin (void)
Definition at line 136 of file TEMU_main.c.
References do_disable_emulation(), plugin_interface_t::plugin_cleanup, plugin_handle, taintcheck_cleanup(), temu_plugin_path, temulog, and term_printf().
Referenced by TEMU_load().
void TEMU_after_iret_protected (void)
Definition at line 557 of file TEMU_main.c.
References plugin_interface_t::after_iret_protected.
void TEMU_after_loadvm (const char * param)
Definition at line 285 of file TEMU_main.c.
References plugin_interface_t::after_loadvm.
Referenced by TEMU_loadvm().
int TEMU_bdrv_pread (void * bs, int64_t offset, void * buf, int count)
Definition at line 488 of file TEMU_main.c.
int TEMU_block_begin ()
Definition at line 494 of file TEMU_main.c.
References plugin_interface_t::block_begin, and TEMU_emulation_started.
void TEMU_block_end ()
Definition at line 505 of file TEMU_main.c.
References plugin_interface_t::block_end, and should_monitor.
void TEMU_call_analysis (uint32_t next_eip)
Definition at line 658 of file TEMU_main.c.
References plugin_interface_t::call_analysis, should_monitor, and TEMU_emulation_started.
void TEMU_do_interrupt (int intno, int is_int, target_ulong next_eip)
Definition at line 550 of file TEMU_main.c.
References plugin_interface_t::do_interrupt.
uint32_t TEMU_get_physaddr_with_cr3 (target_ulong cr3, target_ulong addr)
Definition at line 406 of file TEMU_main.c.
References first_cpu.
Referenced by TEMU_memory_rw_with_cr3().
void TEMU_init ()
Definition at line 763 of file TEMU_main.c.
References register_savevm(), taintcheck_init(), TEMU_load(), and TEMU_save().
void TEMU_insn_begin (uint32_t pc_start)
Definition at line 513 of file TEMU_main.c.
References plugin_interface_t::insn_begin, insn_tainted, should_monitor, and TEMU_emulation_started.
void TEMU_insn_end ()
Definition at line 527 of file TEMU_main.c.
References plugin_interface_t::insn_end, insn_tainted, should_monitor, and TEMU_emulation_started.
static int TEMU_load (QEMUFile * f, void * opaque, int version_id) [static]
Definition at line 709 of file TEMU_main.c.
References do_disable_emulation(), do_enable_emulation(), do_load_plugin(), do_unload_plugin(), guestlog, plugin_handle, qemu_get_be32(), and qemu_get_buffer().
Referenced by TEMU_init().
void TEMU_loadvm (void * opaque)
Definition at line 635 of file TEMU_main.c.
References do_load_plugin(), do_loadvm(), and TEMU_after_loadvm().
int TEMU_memory_rw_with_cr3 (target_ulong cr3, uint32_t addr, void * buf, int len, int is_write)
Definition at line 443 of file TEMU_main.c.
References cpu_physical_memory_rw(), and TEMU_get_physaddr_with_cr3().
Referenced by TEMU_read_mem_with_cr3(), and TEMU_write_mem_with_cr3().
void TEMU_nic_in (uint32_t addr, int size)
Definition at line 221 of file TEMU_main.c.
References taintcheck_nic_in(), and TEMU_emulation_started.
void TEMU_nic_out (uint32_t addr, int size)
Definition at line 211 of file TEMU_main.c.
References taintcheck_nic_out(), and TEMU_emulation_started.
void TEMU_nic_receive (const uint8_t * buf, int size, int cur_pos, int start, int stop)
Definition at line 196 of file TEMU_main.c.
References plugin_interface_t::nic_recv.
void TEMU_nic_send (uint32_t addr, int size, uint8_t * buf)
Definition at line 204 of file TEMU_main.c.
References plugin_interface_t::nic_send.
void TEMU_read_keystroke (void * s)
Definition at line 235 of file TEMU_main.c.
References plugin_interface_t::send_keystroke, and TEMU_KbdState.
static void TEMU_register_rw (int reg_id, void * buf, int is_write) [static]
Definition at line 291 of file TEMU_main.c.
References size.
Referenced by TEMU_read_register(), and TEMU_write_register().
static void TEMU_save (QEMUFile * f, void * opaque) [static]
Definition at line 669 of file TEMU_main.c.
References qemu_put_be32(), qemu_put_buffer(), size, TEMU_emulation_started, and temu_plugin_path.
Referenced by TEMU_init().
void TEMU_update_cpustate ()
Definition at line 160 of file TEMU_main.c.
References first_cpu, TEMU_cc_op, TEMU_cpu_cr, TEMU_cpu_df, TEMU_cpu_eflags, TEMU_cpu_eip, TEMU_cpu_fp_stt, TEMU_cpu_fptags, TEMU_cpu_fpuc, TEMU_cpu_fpus, TEMU_cpu_hflags, TEMU_cpu_regs, and TEMU_eflags.
void TEMU_update_cr3 ()
Definition at line 541 of file TEMU_main.c.
References plugin_interface_t::monitored_cr3, and should_monitor.
void TEMU_virtdev_init ()
Definition at line 270 of file TEMU_main.c.
References guestlog, and TEMU_virtdev_write_data().
static void TEMU_virtdev_write_data (void * opaque, uint32_t addr, uint32_t val) [static]
Definition at line 251 of file TEMU_main.c.
References plugin_interface_t::guest_message, and guestlog.
Referenced by TEMU_virtdev_init().
Variable Documentation
CPUState* first_cpu
Referenced by TEMU_get_page_access(), TEMU_get_phys_addr(), TEMU_get_physaddr_with_cr3(), and TEMU_update_cpustate().
FILE* guestlog = NULL [static]
Definition at line 249 of file TEMU_main.c.
Referenced by procmod_init(), TEMU_load(), TEMU_virtdev_init(), and TEMU_virtdev_write_data().
void* plugin_handle = NULL [static]
Definition at line 57 of file TEMU_main.c.
Referenced by do_load_plugin(), do_unload_plugin(), and TEMU_load().
int should_monitor = 1
this flag indicates whether the plugin should receive callback
Definition at line 28 of file TEMU_main.c.
Referenced by taintcheck_check_eip(), taintcheck_jnz_T0_label(), TEMU_block_end(), TEMU_call_analysis(), TEMU_insn_begin(), TEMU_insn_end(), and TEMU_update_cr3().
uint32_t TEMU_eflags = 0
Definition at line 50 of file TEMU_main.c.
Referenced by TEMU_update_cpustate().
void* TEMU_KbdState = NULL
Definition at line 233 of file TEMU_main.c.
Referenced by TEMU_read_keystroke().
plugin_interface_t* temu_plugin = NULL
Definition at line 27 of file TEMU_main.c.
Referenced by __attribute__(), default_taint_propagate(), fast_clean_memory(), fast_taint_memory(), LIST_HEAD(), reg2reg_internal(), taintcheck_check_eip(), taintcheck_check_virtmem(), taintcheck_chk_hdin(), taintcheck_chk_hdout(), taintcheck_chk_hdread(), taintcheck_chk_hdwrite(), taintcheck_create(), taintcheck_disk_check(), taintcheck_jnz_T0_label(), taintcheck_load(), taintcheck_memory_check(), taintcheck_nic_in(), taintcheck_nic_out(), taintcheck_nic_readbuf(), taintcheck_nic_writebuf(), taintcheck_register_check(), taintcheck_save(), taintcheck_sidt(), taintcheck_taint_memory(), taintcheck_taint_register(), and taintcheck_taint_virtmem().
char temu_plugin_path[PATH_MAX] = "" [static]
Definition at line 58 of file TEMU_main.c.
Referenced by do_load_plugin(), do_unload_plugin(), and TEMU_save().
FILE* temulog = NULL [static]
Definition at line 56 of file TEMU_main.c.
Referenced by do_load_plugin(), and do_unload_plugin().