TEMU: xed-inst.h File Reference
TEMU: Dynamic Binary Analysis Platform
xed2-intel64/include/xed-inst.h File Reference
Data Structures
struct xed_inst_s
struct xed_operand_s
Typedefs
typedef struct XED_DLL_EXPORT
xed_inst_s xed_inst_t
typedef void(* xed_operand_extractor_fn_t)(struct xed_decoded_inst_s *xds)
typedef struct XED_DLL_EXPORT
xed_operand_s xed_operand_t
Variables
XED_DLL_GLOBAL const xed_operand_t xed_operand [XED_MAX_OPERAND_TABLE_NODES]
xed_inst_t Attribute access
XED_DLL_EXPORT xed_attribute_enum_t xed_attribute (unsigned int i)
XED_DLL_EXPORT unsigned int xed_attribute_max ()
static XED_INLINE xed_uint32_t xed_inst_get_attribute (const xed_inst_t *p, xed_attribute_enum_t attr)
static XED_INLINE xed_uint64_t xed_inst_get_attributes (const xed_inst_t *p)
xed_inst_t Template Instruction Information
static XED_INLINE
xed_category_enum_t xed_inst_category (const xed_inst_t *p)
static XED_INLINE
xed_extension_enum_t xed_inst_extension (const xed_inst_t *p)
XED_DLL_EXPORT xed_uint32_t xed_inst_flag_info_index (const xed_inst_t *p)
static XED_INLINE xed_iclass_enum_t xed_inst_iclass (const xed_inst_t *p)
static XED_INLINE xed_iform_enum_t xed_inst_iform_enum (const xed_inst_t *p)
static XED_INLINE
xed_isa_set_enum_t xed_inst_isa_set (const xed_inst_t *p)
xed_inst_t Template Instruction Information
XED_DLL_EXPORT unsigned int xed_inst_cpl (const xed_inst_t *p)
static XED_INLINE unsigned int xed_inst_noperands (const xed_inst_t *p)
static XED_INLINE const
xed_operand_t * xed_inst_operand (const xed_inst_t *p, unsigned int i)
xed_inst_t Template Operand Read/Written
XED_DLL_EXPORT xed_uint_t xed_operand_conditional_read (const xed_operand_t *p)
XED_DLL_EXPORT xed_uint_t xed_operand_conditional_write (const xed_operand_t *p)
XED_DLL_EXPORT xed_uint_t xed_operand_read (const xed_operand_t *p)
XED_DLL_EXPORT xed_uint_t xed_operand_read_and_written (const xed_operand_t *p)
XED_DLL_EXPORT xed_uint_t xed_operand_read_only (const xed_operand_t *p)
static XED_INLINE
xed_operand_action_enum_t xed_operand_rw (const xed_operand_t *p)
XED_DLL_EXPORT xed_uint_t xed_operand_written (const xed_operand_t *p)
XED_DLL_EXPORT xed_uint_t xed_operand_written_only (const xed_operand_t *p)
xed_inst_t Template Operands Access
static XED_INLINE xed_uint32_t xed_operand_imm (const xed_operand_t *p)
static XED_INLINE
xed_operand_enum_t xed_operand_name (const xed_operand_t *p)
static XED_INLINE
xed_nonterminal_enum_t xed_operand_nonterminal_name (const xed_operand_t *p)
static XED_INLINE
xed_operand_visibility_enum_t xed_operand_operand_visibility (const xed_operand_t *p)
XED_DLL_EXPORT void xed_operand_print (const xed_operand_t *p, char *buf, int buflen)
static XED_INLINE xed_reg_enum_t xed_operand_reg (const xed_operand_t *p)
static XED_INLINE xed_uint_t xed_operand_template_is_register (const xed_operand_t *p)
static XED_INLINE
xed_operand_type_enum_t xed_operand_type (const xed_operand_t *p)
static XED_INLINE
xed_operand_width_enum_t xed_operand_width (const xed_operand_t *p)
xed_inst_t Template Operand Enum Name Classification
static XED_INLINE xed_uint_t xed_operand_is_memory_addressing_register (xed_operand_enum_t name)
static XED_INLINE xed_uint_t xed_operand_is_register (xed_operand_enum_t name)
Typedef Documentation
typedef void(* xed_operand_extractor_fn_t)(struct xed_decoded_inst_s *xds)
Definition at line 56 of file xed2-intel64/include/xed-inst.h.
Function Documentation
static XED_INLINE xed_category_enum_t xed_inst_category (const xed_inst_t * p) [static]
Definition at line 257 of file xed2-intel64/include/xed-inst.h.
References xed_iform_to_category().
static XED_INLINE xed_extension_enum_t xed_inst_extension (const xed_inst_t * p) [static]
Definition at line 261 of file xed2-intel64/include/xed-inst.h.
References xed_iform_to_extension().
XED_DLL_EXPORT xed_uint32_t xed_inst_flag_info_index (const xed_inst_t * p)
static XED_INLINE xed_iclass_enum_t xed_inst_iclass (const xed_inst_t * p) [static]
Definition at line 253 of file xed2-intel64/include/xed-inst.h.
References xed_iform_to_iclass().
static XED_INLINE xed_iform_enum_t xed_inst_iform_enum (const xed_inst_t * p) [static]
Definition at line 268 of file xed2-intel64/include/xed-inst.h.
static XED_INLINE xed_isa_set_enum_t xed_inst_isa_set (const xed_inst_t * p) [static]
Definition at line 264 of file xed2-intel64/include/xed-inst.h.
References xed_iform_to_isa_set().
Variable Documentation
XED_DLL_GLOBAL const xed_operand_t xed_operand[XED_MAX_OPERAND_TABLE_NODES]